pydicom/pydicom

pydicom/dataset.py
pydicom/misc.py
tests/test_misc.py

Why? So a user can do things like this:
``with pydicom.read_file('mydicom.dcm') as dcm:`` which will elegantly handle object destruction (Dataset). This is useful for large dicom files or when a user only wants the information of a few tags. I should add that this adds context to the returned object, not the file object that was passed. I'm unsure of behavior for a file object passed with such behavior (I never use it that way).
Why Dataset? 
It took me a while to figure out exactly what needs to happen, but in the end, whatever ``object`` gets returned in the ``with`` statement has to have the ``__enter__()`` and ``__exit__()`` methods, which, in the case of read_file, read_partial, is a Dataset. This could also be put into FileDataset; I'm not sure if one is preferable or not. I found …

added context management methods to Dataset & is_dicom function

---

pydicom/dataelem.py
pydicom/util/fixer.py

Adds a callback function that checks if a raw data element is translatable with its VR. If it is not, translation is re-attempted with a configurable set of other VRs.  If a useable translator is found, then the raw data element is 'fixed' with the useable VR. 
I also changed `dataelem.DataElement_from_raw` to check the VR after the callback function.  This allows a change to data element's VR to get used for the actual translation.
Thoughts?

add callback fxn to translate value-vr mismatches

---

source/dicom/test/test_unicode.py

The problem comes when e.g. using on systems with LC_ALL=C on Linux -- encoding would fail to that locale.  Alternative resolution could be to force utf8 encoding but wasn't sure if that would be "kosher" so decided just to skip the test (since you don't use any specific additional platform like nose, I just printed "skip" to stay compatible with older unittest's)
```
Index: pydicom-0.9.9/source/dicom/filereader.py
===================================================================
--- pydicom-0.9.9.orig/source/dicom/filereader.py
+++ pydicom-0.9.9/source/dicom/filereader.py
@@ -586,7 +586,9 @@ def read_file(fp, defer_size=None, stop_
caller_owns_file = False
logger.debug(u"Reading file '{0}'".format(fp))
-        fp = open(fp, 'rb')
+        # yoh: it might encode into file system …
```

BF: do not force unicode names when not supported

---

pydicom/valuerep.py

I believe the intention of using a single quoted string as a
representation is to prevent the introduction of floating point rounding
errors.
This change means that DSFloats (etc) can be correctly encoded with the
default python JSON library. Currently, the value is single-quoted in
the JSON, causing a parse error when trying to run json.loads().
Changing to double quotes should preserve the intended effect whilst
allowing JSON-based marshalling to work.
----
That's unless there's a reason single quotes are used. I've run the tests locally with success, with the exception of some (unrelated, I think) JPEG2000 tests.

change __repr__ to use double quotes for numerics

---

pydicom/datadict.py
pydicom/dataelem.py
pydicom/dataset.py
tests/test_dataelem.py
tests/test_dataset.py

- Brings DataElement attributes into line with the information available in PS3.6 Table 6-1.
- Adds unit test for #253, unit tests for DataElement's new keyword and is_retired attributes
- Adds information about DataElement's attributes to its docstring

Add keyword and is_retired attributes to DataElement, docstring update, unit tests

---

pydicom/multival.py
tests/test_multival.py

Replacing generator expression with listcomp will ensure we are not iterating over a potentially mutating list. This issue arose after upgrading pydicom from version 0.9.6 -> 0.9.9 caused a regression in one of our unit tests.

Fix infinite loop in MultiValue.extend when extending with self

---

pydicom/dataset.py
tests/test_filereader.py

This is a test case and a fix for the issue raised in pull request #257  
The actual test file is uncomfortably large, but I could not get either gdcm or dcmtk to properly downsize it.  When I used gdcm to decompress it, it also seemed to corrupt the last two channels (eg, a pixel showing values (57, 57, 57) in Osirix viewer on the original, would show (57, 128, 128) after being decompressed with gdcm.)  The test case asserts that the pixel data shape is as expected and that two example pixels are correctly decoded.

Test case and fixes for 3d color jpeg issue

---

pydicom/dataset.py

This is a fix for https://github.com/darcymason/pydicom/issues/270 - basically GDCM was returning a large byte array that had a lot of padding with zeros at the end.

Fix a bug that occurred when GDCM returned a buffer that was longer than the data

---

pydicom/contrib/pydicom_PIL.py

Create separate get_PIL_image function to retrieve the PIL image object itself, instead of displaying it immediately.

Create get_PIL_image function in pydicom_PIL.py

---

pydicom/filewriter.py
pydicom/values.py
tests/test_filereader.py
tests/test_filewriter.py

I noticed that pydicom does no endianness conversion when reading/writing OW byte data so I didn't include any for these two (plus big endian was retired last year). If I'm wrong about that, let me know.
Related to #304, #295 and #216.

Added support for elements with a VR of OD and OL

---

pydicom/dataset.py
pydicom/tag.py
tests/test_tag.py

* Added missing operators (`__le__`, `__gt__`, `__ge__`) to `BaseTag` (to ensure consistent behaviour with `__lt__` and `__eq__`) and refactored `__ne__`
* Added ability to use a single `str` when creating a `Tag`, i.e. `Tag('0x00100010')`
* `ValueError` now raised when attempting to create a negative `Tag`
* `ValueError` now raised when attempting to create a `Tag` using `Tag(0x10, '0x02')` (consistent with `ValueError` for `Tag('0x10', 0x20)`)
* Updated/expanded unit tests for tag module
* Minor docstring changes for `Dataset`

Changes to Tag and BaseTag, unit tests for tag module, minor docstring update for Dataset

---

pydicom/filewriter.py
tests/test_filewriter.py

* Added unit tests for `_write_file_meta_info`.
* `ValueError` now raised if non Group 2 elements present in the File Meta.
* `file_meta.MetaInformationGroupLength` value now set correctly (issue #326).
* Refactored `_write_file_meta_info` to make it more readable.
* Expanded docstring

Add unit tests, updates for _write_file_meta_info

---

pydicom/filereader.py
tests/test_filereader.py

- prevents rare crash if reading data with defer_size less than Specific
Character Set value length

Make sure that Specific Character Set is always read

---

pydicom/filebase.py
tests/test_filereader.py
tests/test_filewriter.py

Closes: https://github.com/darcymason/pydicom/issues/313
Partially addresses: https://github.com/darcymason/pydicom/issues/310

make DicomBytesIO a class rather than a function

---

pydicom/datadict.py
pydicom/dataelem.py
pydicom/dataset.py
tests/test_dataelem.py
tests/test_dataset.py
tests/test_dictionary.py

* Element name added to `DataElement` string output for repeater group elements.
* Adding repeater group elements to `Dataset` via keyword (eg `ds.OverlayData = x`) now raises `ValueError` instead of creating a `Dataset` attribute.
* Added two `datadict.py` functions `repeater_has_keyword` and `repeater_has_tag`
* Unit tests for the above

Repeater Group element improvements

---

pydicom/dataset.py
tests/test_dataset.py

Fix for catching redundant errors during exceptions as in [this traceback](https://groups.google.com/forum/#!msg/pydicom/TD1dY8r-oZA/yiXrG_ctAgAJ) and unit test updated to match.

Refactor Dataset.__getattr__ and pixel_array to remove multiple redundant exceptions

---

pydicom/filereader.py
tests/test_filereader.py
tests/test_filewriter.py

* Fix for the failed dataset read in #340 (no preamble + group 2 elements meant the remainder of the dataset was read using explicit VR rather then implicit)
* Refactor of `read_partial`:
* Ensure that both Command Set and File Meta Info elements are read with correct transfer syntax even if the preamble is missing
* Ensure that with missing file meta transfer syntax, the attempt to determine the correct value is made using the first non-group 0/2 element in the dataset.
* Eliminated failure mode if Command Set Group Length is present but no transfer syntax set
* Removed pydicom adding a TransferSyntaxUID element to the `file_meta` if none present during read (still gets added during file write even with `write_like_original` set to True). 
* Refactored `_read_file_meta_info` to eliminate …

Fixes/refactor for dataset reading, unit tests

---

pydicom/dataset.py
tests/test_dataset.py

* Fixes for `Dataset.data_element` and `Dataset.__contains__` not handing (0000,0000) properly.
* Add unit tests for `Dataset.iterall`, `Dataset.data_element`, `Dataset.remove_private_tags`, `Dataset.get_item`, `Dataset.group_dataset`.
* Add Dataset slicing using element tags to `Dataset.__getitem__` and `Dataset.__delitem__`, unit testing:
```python
ds = read_file('file-in.dcm')
new_ds = ds[:(0x0001,0x0000)] # Get all group 0000 elements
new_ds = ds[0x00080000:0x00080012] # Get all elements from (0008,0000) to (0008,0012)
del ds[:(0x0001,0x0000)] # Delete all group 0000 elements
```

Add Dataset slicing, unit tests, bug fixes

---

pydicom/filebase.py

Closes #371.
Python < 3.4:
No expected change in behaviour as `DicomIO.__del__` won't be called as its not being garbage collected.
Python >= 3.4:
`filewriter.file_write()` no longer closes the passed `filename` object if its a `DicomIO` subclass.

Remove __del__ from DicomIO to fix memory leak in python < 3.4

---

.pep8speaks.yml

A pep8 configuration replicating most of the configuration in `.pep8` config file.

[MRG+1] Add first version of pep8speaks

---

setup.py

closes #403 
Remove numpy from the `setup.py` such that pip does not install it.

[MRG] Remove numpy as depency by default

---

.pep8speaks.yml

continues #396 
Use the default PEP8, while keeping the `.pep8speaks.yml` so that we can keep track to any change of the pep8 enforcement.

[MRG+1] Enforce the entire PEP8

---

pydicom/filereader.py
pydicom/tests/test_charset.py
pydicom/tests/test_filereader.py

- closes #95
Added `specific_tags` argument to `filereader.read_file` and related methods, as proposed by @darcymason.
If set, only the specified tags are read.
I tried to measure the performance but could not see significant improvements if reading only specific tags. If any, the improvements are only on the first read - after that, the file cache pretty much equals it out.

[MRG+2] Added possibility to read only specific tags

---

pydicom/dataelem.py
pydicom/tests/test_dataelem.py

- fixes #123
`dataelem.DataElement_from_raw` has a second encoding parameter that is needed in Python 3.
With default value `None` for this parameter it could raise under Python 2, which was not intented.
This just replaces this default parameter with a sensible one under Python 2.

[MRG+2] Allow no encoding in DataElement_from_raw in Python 2

---

pydicom/fileutil.py

Update the read_size of read_undefined_length_value() to 8KiB to improve performance. Closes #436
After profiling, the read_size of read_undefined_length_value() is too low at 128B. Increasing it to a few kilobyted greatly improves performance (15MB file by x4; 50MB file by x10).

[MRG+2] Update the read_size of read_undefined_length_value() to 8KiB #436

---

pydicom/tests/test_valuerep.py
pydicom/values.py

- moved unreachable code, removed unused code
Minor change: noticed problem with error handling logic while working on another issue.
Code in `else` part was unreachable due to `break` before, fallback was not used.
to be listed in #428

[MRG + 2] Remove unreachable code in  convert_value at pydicom/values.py

---

pydicom/dataset.py
pydicom/filebase.py
pydicom/filewriter.py

Fixes issue #444
Fixes generic_jpeg_file_header from being a tuple of bytes to bytes by joining.

[MRG+2] Fix generic_jpeg_file_header from being a tuple of bytes

---

pydicom/datadict.py
pydicom/tests/test_dictionary.py

- fixes #441
Fixes a simple mistake. I searched the code for similar problems, but this the only one of this kind.

[MRG+2] Fixed mistake in splitting format string

---

pydicom/filebase.py
pydicom/tests/test_filereader.py
pydicom/tests/test_filewriter.py

- avoids EOFError for standard invocation to match default read behavior
- fixes #358
See #358: currently, DicomIO.read() raises an exception by default, if the number of read bytes is less than the length argument. This does not match the standard behavior of other read() functions and leads to unexpected behavior (in the given case just an incorrect warning).
The argument `need_exact_length` controls this behavior - if it is set to False (now the default) the exception is not raised. Where it was needed, the code has been adapted.

[MRG+1] DicomIO.read: changed default for need_exact_length to False

---

appveyor.yml

Only Python 3.4 was loaded in appveyor because the path to the binary was wrong.

[MRG+1] CI/FIX load right python version in appveyor

---

pydicom/pixel_data_handlers/rle_handler.py

Improves the performance of the RLE plane decoder by eliminating a list construction and an arithmetic operation.
MR_small_RLE.dcm is about 25% faster (2.8 s vs 3.7 s for n = 10000).
emri_small_RLE.dcm is about 35% faster (11.5 s vs 18.3 s for n = 10000).

[MRG + 2] Performance improvement for RLE decoder

---

pydicom/charset.py

[MRG+2] Update charset.py

---

pydicom/dataset.py
pydicom/tests/test_dataset.py

Fixes #486
`Dataset.__dir__ `now class specific

[MRG+1] Fix dir(Dataset) not working correctly for subclasses

---

pydicom/filewriter.py
pydicom/tests/test_filewriter.py

- pixel data with undefined length shall start with an item delimiter
- fixes #238 by raising an exception that clarifies the problem
see discussion in #238

[MRG] Raise ValueError for invalid pixel data with undefined length

---

pydicom/tests/test_uid.py
pydicom/uid.py

- fixes #499
- avoids infinite recursion while accessing UID properties if the UID happens to have the same hash as a predefined UID

[MRG+2] Avoid infinite recursion in UID properties

---

pydicom/filereader.py
pydicom/tests/test_filereader.py

Fixes #503 
When reading a DICOM file with an implicit VR file meta, pydicom raises a NotImplementedError (Unknown Value Representation), as it tries to read the file meta as explicit VR. This edit catches the exception and retries to read the file meta using the implicit VR.
It seems that my edits do not affect the unit tests (the same number of tests fail on my machine when I switch to the master branch), but I'm not entirely sure if I run them correctly. I did not yet add a unit test for my edits: would that be required?

[MRG+2] Fixes problem for files with implicit VR file meta - closes #503

---

pydicom/multival.py
pydicom/tests/test_multival.py

- see https://github.com/pydicom/contrib-pydicom/issues/5
For more convenient usage of ``MultiValue`` inline sorting has been added, as used in ``pydicom_series.py`` (see mentioned issue).

[MRG+2] Added possibility to inline sort MultiValue

---

build_tools/travis/install.sh

- fixes #507
Uninstalling the old wheel package while installing the new one caused a permission problem, probably because the package was in use. As wheel is already installed, there is no need to replace it.

[MRG] Do not install already installed wheel package

---

pydicom/tests/test_dataset.py

failUnlessRaises is now based off of the Python 2.5 unittest function.
Removes Creative Commons Share-Alike content.

Refactor failUnlessRaises

---

pydicom/uid.py
pydicom/valuerep.py

This PR fixes escape sequences that are deprecated in Python 3.6 by using raw strings/bytes.
https://docs.python.org/3/whatsnew/3.6.html#deprecated-python-behavior

[MRG] Fix escape sequences that are deprecated in Python 3.6

---

pydicom/filereader.py
pydicom/tests/test_charset.py
pydicom/tests/test_dataset.py
pydicom/tests/test_dicomdir.py
pydicom/tests/test_encaps.py
pydicom/tests/test_errors.py
pydicom/tests/test_filebase.py
pydicom/tests/test_filereader.py
pydicom/tests/test_filewriter.py
pydicom/tests/test_misc.py
pydicom/tests/test_uid.py
pydicom/tests/test_values.py

- replaced assert_raises_regex() with standard with pytest.raises()
- removed empty tests
- minor formatting changes
- closes #543
Implemented most of the review comments, with 2 exceptions:
- I removed the empty tests instead of marking them (they should probably be implemented next time one of the untested classes is touched)
- I left a TODO in the code (hexutil.hex2bytes) with the corresponsing tests skipped - I will handle this another day either by writing a separate issue, or providing a PR

[MRG+1] Implemented review comments for #465

---

pydicom/datadict.py

Fixes #554.
Adds the pydicom < 1.0 `tag_for_name` function back in for DeprecationWarning purposes.   Does not have complete functionality of the old one, i.e. it does not accept names other than dicom keywords.  
The old pydicom short names, etc. will still throw an error, so this is not completely backwards compatible.

Add tag_for_name back in with deprecation warning

---

pydicom/pixel_data_handlers/pillow_handler.py

#539 demonstrates that Pillow does not handle lossy JPEG 2000 compression properly. Such unstable behaviour should probably be disabled by default.
I can't see any existing tests that this change would break as the lossy JPEG file (`JPEG2000.dcm`) is not being decompressed there.

Remove lossy JPEG 2000 from PIL-supported formats

---

pydicom/compat.py
pydicom/tag.py
pydicom/tests/test_tag.py

… even if they are different
- handles the case with mixed int and long in Python2
- fixes #553

[MRG] Tag can be constructed from a list of two integral types now

---

pydicom/misc.py
pydicom/tests/test_misc.py

- fixes #555
Note - there is not math.inf before Python 3.5.

[MRG] Allow defer_size to be infinite

---

pydicom/tests/test_pillow_pixel_data.py

- support has been removed due to incorrect pillow implementation

[MRG] Do not try to test Jpeg2000 lossy image with pillow

---

pydicom/misc.py
pydicom/tests/test_util.py
pydicom/util/hexutil.py

- misc.is_dicom():
* rely on Python to raise the correct exception
* make sure the tested file is closed
- hexutil.hex2bytes(): raise TypeError for incorrect type
Just a couple of ToDos I noticed in the code. As there is also a bug involved (file not closed if calling `is_dicom()`) I would want to merge this.

[MRG] Remove some ToDo comments

---

appveyor.yml
build_tools/circle/build_doc.sh
build_tools/travis/install.sh
pydicom/__init__.py
pydicom/_version.py
pydicom/filewriter.py
pydicom/tests/test_filewriter.py

To actually benefit from bumpversion, `__version_info__` should be automatically inferred from `__version__`.

[WIP] FIX infer __version_info__ from __version__

---

doc/working_with_pixel_data.rst
examples/image_processing/plot_downsize_image.py
pydicom/pixel_data_handlers/gdcm_handler.py
pydicom/pixel_data_handlers/jpeg_ls_handler.py
pydicom/pixel_data_handlers/numpy_handler.py
pydicom/pixel_data_handlers/pillow_handler.py
pydicom/tests/test_dataset.py
pydicom/tests/test_filebase.py
pydicom/tests/test_filereader.py
pydicom/tests/test_filewriter.py
pydicom/values.py

- replaced numpy.fromstring() by frombuffer()
- replaced assertRaisesRegexp() by pytest.raises()
- make sure opened files are closed
- replaced warn() by warning()
- fixes #559
There is one place in the pillow handler I'm not sure about: I replaced `numpy.fromstring()` by `numpy.copy(numpy.frombuffer())` (the copy is needed because afterwards the highest bit is masked out). This should basically do the same, but I'm not sure if it may be a performance problem. 
Someone with better numpy knowledge please comment.

[MRG] Fixed pytest warnings

---

dicom.py
pydicom/_version.py
setup.cfg
setup.py

Fixes #582 as an alternate choice to PR #583.
Provides a mechanism for a mock `import dicom` if no `dicom` already exists on installation.  With this patch, if someone installs the latest pydicom (>=1.0), then `import dicom` will provide a message and an ImportError exception.

Provide mock 'dicom' import with helpful transition information

---

pydicom/filewriter.py
pydicom/tests/test_filewriter.py

- fixes #489
Note - I had to change the unicode value to a latin1-compatible one in one test because it uses the standard encoding, which is usually latin-1 under Windows.

[MRG+1] Handle the case where encoding is given as a list in Python 2

---

pydicom/dataset.py
pydicom/tests/test_dataset.py
pydicom/tests/test_filewriter.py

Fixes #92 
When slicing to the end of a Dataset containing a (0xFFFF, 0xFFFF) element, the slice no longer causes an OverflowError

[MRG+1] Fix for Dataset slicing not working correctly for (0xFFFF, 0xFFFF)

---

pydicom/filewriter.py
pydicom/tests/test_filewriter.py

- as recommended by PS3.5, chapter 7.2
- closes #32
I did the removal unconditionally and didn't add an option as discussed in the issue - the removal seems to have no effect on tests, and I would rather not add complexity if not needed here.

[MRG+1] Remove Group Length while writing a data set

---

build_tools/travis/install.sh

- fixes permission problem if trying to install pip over an existing pip

[MRG + 1] Do not install pip twice for pypi

---

pydicom/dataset.py
pydicom/filereader.py
pydicom/tag.py

- closes #605
This is a trivial change to avoid all the checks in `Tag` (well, all but the new check) if the key is already a `BaseTag`, which is the case in the writing code.
This reduces the write time for my test data set from 627 to 410 msec (the reference in pydicom 0.9.9 took 388 msec, so there is still way for improvement).
EDIT: after the second commit, write performance is about the same as in 0.9.9.

[MRG+1] Added check for BaseTag in Tag() to avoid costly checks

---

pydicom/dataset.py
pydicom/filewriter.py

- slightly improved write code
- use BaseTag instead of string in often called method
This gains another few percent (3-7% in my tests) in writing performance.

[MRG] Minor consolidation of previous change

---

pydicom/dataelem.py
pydicom/tag.py
pydicom/tests/test_filewriter.py
pydicom/tests/test_tag.py

- see PS3.5 6.2.2 and 7.8.1
- see #620 
Private tag VR was always set to OB. I'm not sure if we also shall take into account the private dictionary while reading private tags from implicit VR files, so I left that out - if it is wanted, I can add this.

[MRG + 1] Use correct VR for unknown private tags and private creators

---

pydicom/pixel_data_handlers/numpy_handler.py
pydicom/tests/test_numpy_pixel_data.py

Aims to resolve the problem identified in https://github.com/pydicom/pydicom/pull/293#pullrequestreview-109529983
* bits were unpacked from the left, which was incorrect, see discussion in
https://github.com/pydicom/pydicom/pull/293#pullrequestreview-109529983.
Correct unpack order implemented now, whereas first pixel from the left in
the image frame corresponds to the first bit from the right in the packed
PixelData
* fixed consistency checks verifying the size of the PixelData
* reordered the code to perform unpacking after consistency checks
* removed the dependency on numpy.unpackbits and the associated exception
The functionality of the code was verified using the DICOM Segmentation image
dataset being developed in this PR (3x23x38, which illustrates a case where
bits of the …

[MRG+1] Fix handling of bit-packed PixelData

---

pydicom/datadict.py

- cache repeater keywords for faster lookup
- see #621
The repeater tag lookup was at the top of the cProfile output, so this is an easy fix.
For the SR file I tested (which has a lot of sequences as most SR have) this decreased the read time by 30% - not that much, but I thought it is worth the small change.

[MRG+1] Slight improvement of read performance of sequences

---

pydicom/tests/test_valuerep.py
pydicom/valuerep.py

Fixes issue #640 
Fixing issue 640: in Python 2, creating a valuerep IS() with an integer too long would raise an OverflowError. This is handled already in the code with config.enforce_valid_values if the developer decides to use it. Python 3 seems to be behaving differently.
We're just using the regular int() casting method if the built-in super() function doesn't work.

[MRG+1] Fixing issue #640, OverflowError for valuerep IS

---

README.md
setup.py

- avoids duplication of description
I noticed that the description in Pypi had a wrong link, so I thought it a good idea to avoid having separate descriptions on GitHub and PyPi and just use the README.md.
This is possible since the new PyPi site is up and running - you can check how it looks on the [PyPi test page](https://test.pypi.org/project/pydicom-test/).

[MRG] Use README.md as long description for PyPi

---

doc/whatsnew/v1.1.0.rst

- added proper links to related issues
Here is the [preview](https://10-65673081-gh.circle-artifacts.com/0/home/ubuntu/pydicom/doc/_build/html/whatsnew/v1.1.0.html).
I scanned all check-ins from the last release - if there will be more before the release, we have to add that, of course.

Updated release notes for 1.1.0 release

---

.travis.yml
pydicom/tests/test_fixes.py

- added Tracis config for Python 3.7
- fixes #668

[MRG] Execute date time tests only for the backport to Python 2

---

doc/whatsnew/v1.2.0.rst
pydicom/dataelem.py
pydicom/tests/test_dataelem.py
pydicom/tests/test_valuerep.py
pydicom/valuerep.py

None, afaict.
Adds `__repr__` method to `DA`, `TM`, and `DT` values, to make them symmetrical to `IS` and `DS`.
This allows consumers to be able to obtain the original string as the representation of the `DA`/`TM`/`DT` object, instead of something like: `DA(2018, 6, 18)`
While going through this issue, I also notice that the `DataElement.repval` property tries to use the `original_string` attribute in order to print out the representation string, before falling back to `repr(self.value)`
This, on its own, is fine. However, as far as I could tell, `original_value` is not used/set in `DataElement` instances, but in value instances (`IS`, `DSfloat`, ...) so the `elif` clause in line `pydicom/dataelem.py:307` is never true.
Since I'm not sure I'm missing something here, I just added an extra …

[MRG+2] DA, TM, DT repval fix

---

.circleci/config.yml

- docs have not been pushed due to the expression failing
- see #656
Note I didn't succeed to test the actual push in my branch - I only checked that it was executed, but the checkout failed due to the wrong branch.

[MRG] Fixed syntax of regex check used for doc deployment

---

.circleci/config.yml

Another attempt at fixing #674 
This time add the SSH deploy key fingerprint to the Circle config as specified [here](https://circleci.com/docs/2.0/gh-bb-integration/#deployment-keys-and-user-keys)

[MRG] Add deploy fingerprint to circle config

---

doc/whatsnew/v1.2.0.rst
pydicom/dataelem.py
pydicom/tests/test_dataelem.py

Closes #291
Deprecates DeferredDataElement for removal in v1.3

[MRG+1] Deprecate DeferredDataElement

---

doc/release-notes.rst
doc/whatsnew/v1.2.0.rst
pydicom/dataelem.py
pydicom/tests/test_filewriter.py

- all VRs that allow only the default character
repertoire can now be initialized with a byte string
- closes #624

[MRG+1] Allow byte string values for some VRs

---

doc/whatsnew/v1.2.0.rst
pydicom/pixel_data_handlers/jpeg_ls_handler.py
pydicom/pixel_data_handlers/pillow_handler.py
pydicom/tests/test_util.py

#682
Switch to using `bytearray` when building the uncompressed pixel data rather than `bytes`. Also changed one of the test_util tests to use the full filename because it kept using 'rtplan.dump' instead of 'rtplan.dcm'.
Time to read the file uploaded in the issue went from 15.9 seconds to 2.8 in python 3.6 and was 2.9 in python 2.7.
The pixel data handlers could use a refactor

[MRG] Improve performance for multi-frame pixel data

---

pydicom/datadict.py
pydicom/dataelem.py
pydicom/tests/test_dataelem.py

- happened for Implicit Little Endian transfer syntax:
incorrect VR was taken from the repeater tags
- fixes #689

[MRG+1] Do not handle private tags in repeater range as repeater tags

---

pydicom/tests/test_pillow_pixel_data.py

* Converts unit test to pytest
* Cleanup of the imports
* Cleanup of the global variable definitions to make more readable
* A couple of tests adjusted to remove the need to import `numpy.testing`

[MRG+1] Convert to pytest, cleanup imports and globals for pillow pixel handler unit tests

---

.travis.yml
build_tools/travis/install.sh
pydicom/pixel_data_handlers/pillow_handler.py

Fixes #663
* Adds travis builds for pillow without JP2k to reproduce the issue
* Removes the addition of an APP marker with JFIF to the pixel data when handling JPEG Baseline transfer syntaxes with the pillow handler.

[MRG] Fix Pillow pixel data handler for non-JPEG2k transfer syntax

---

pydicom/filewriter.py
pydicom/tests/test_filewriter.py

- always set to OW for Implicit Little Endian (as per standard)
- always set to OB for BitsAllocated <= 8
I got a crash report from a former collegue using pynetdicom3 for multi-frame files with implicit VR, so I checked this code again, and also noticed that it didn't handle data with BitsAllocated = 1 (additionally to multi-frame data). 
Note that the behavior has slightly changed, as described in the commit comment. Additionally, the absence of some tags is not handled as before. The handling (e.g. the attribute error is caught, and the program will crash because of the invalid VR later) has remained for BitsAllocated, though I would find it more logical to not catch that error at all, e.g. raise an attribute error because of the missing tag instead of a later error due to an unhandled …

[MRG] Changed handling of Pixel Data with undefined VR

---

.circleci/config.yml

Fixes #702
gh-pages branch ignored in Circle
I've switched the 'Only build pull requests' option back to 'off'.

[MRG] Ignore gh-pages branch in Circle builds

---

build_tools/circle/push_doc.sh

Related to #702
Add `[skip ci]` to commit messages for `gh-pages` as per [this page](https://circleci.com/docs/2.0/skip-build/#skipping-a-build)

[MRG+1] Tell circle not to build commits to gh-pages

---

pydicom/charset.py
pydicom/tests/test_charset.py

- this avoids warnings on correct values, if not all of multiple values
have to be patched
- use stacktrace=2 for the warning for the stacktrace line to make a bit more sense
- removed code that deleted the first encoding for PN if only one component is present
This is a minor cosmetic change to #695. This came up in the related [pynetdicom3 issue](https://github.com/pydicom/pynetdicom3/issues/201#issuecomment-411740471).

[MRG] Fix the regex for char set values to not include correct values

---

pydicom/dataset.py
pydicom/filereader.py
pydicom/pixel_data_handlers/jpeg_ls_handler.py
pydicom/pixel_data_handlers/numpy_handler.py
pydicom/pixel_data_handlers/pillow_handler.py
pydicom/pixel_data_handlers/rle_handler.py
pydicom/pixel_data_handlers/util.py
pydicom/tests/test_jpeg_ls_pixel_data.py
pydicom/tests/test_numpy_pixel_data.py
pydicom/tests/test_pillow_pixel_data.py

- adapted pixel handlers where endianess is explicitely adapted
- fixes #704

[MRG+1] Raise ValueError if endianess is not set in dataset

---

pydicom/charset.py
pydicom/tests/test_charset.py
pydicom/valuerep.py

- fixes #707
This fixes only the obvious problem that the first encoding was deleted and thus could not be used as the default value. 
Note that I wanted to add more tests for arbitrary multi-value encodings (such as latin1 and cyrillic mixed as in the test), and I couldn't get them to work correctly. The escape codes (the ones defined in PS3.3, Table C.12-3) seem not to be handled at all. I'm not sure if I did something wrong, or this is just not implemented. Also, in case it is not implemented, I'm not sure if this occurs in the real world (I have never seen it), or we can just ignore these cases.

[MRG] Do not remove the first encoding for multiple encodings

---

doc/whatsnew/v1.2.0.rst
pydicom/pixel_data_handlers/pillow_handler.py

Closes #722
Removes PIL as a fallback in the pillow pixel data handler

[MRG+1] Remove PIL as a fallback

---

pydicom/tests/test_charset.py
pydicom/tests/test_valuerep.py
pydicom/valuerep.py
pydicom/values.py

- fixes #629
- minor consolidation of person name code to avoid duplicate code
- converted valuerep tests to pytest, added some tests
I was doing some minor refactoring to prepare further changes and noticed the change to `PersonNameUnicode` in Python 2 is now very easy (after the latest changes), and does not break any tests and current behavior (hopefully). So this is a bit of a mix of the fix and the refactoring - if wanted, I can separate these into 2 commits.

[MRG+1] Use PersonNameUnicode to decode PN in Python 2

---

pydicom/filewriter.py
pydicom/tests/test_dicomdir.py
pydicom/tests/test_encaps.py
pydicom/tests/test_filebase.py
pydicom/tests/test_filereader.py
pydicom/tests/test_filewriter.py
pydicom/tests/test_numpy_pixel_data.py

- raise AttributeError if a type attribute needed for
interpretation is missing
- Waveform tags shall always be OW for Implicit Little Endian
- fixed incorrect tag number (5400,0110)
- set OverlayData always to OW
The issue with Overlay Data not converted came up while converting data from Implicit to Explicit Little Endian in a storescp implementation (causing an exception because of ambiguous VR). As far as I understand, we can always use OW in this case.
Raising AttributeError is similar to the change I made for PixelData before and is clearer IMO than the exception raised because of the ambiguous VR in the calling code - if this is not wanted, I can revert this part.

[MRG+1] Some changes to correct_ambiguous_vr_element

---

pydicom/charset.py
pydicom/tests/test_valuerep.py
pydicom/tests/test_values.py
pydicom/valuerep.py
pydicom/values.py

- support delimiters as defined in PS3.5, section 6.1.2.5.3
- extended tests for PersonNameUnicode
This was missing from the implementation of reading single-value encodings.

[MRG+1] Support resetting delimiters in single-value encodings

---

doc/whatsnew/v1.2.0.rst
pydicom/tests/test_uid.py
pydicom/uid.py

Removes `UID.__eq__`, `UID.__ne__` and `UID.__hash__` as per planned deprecation.

[MRG+1] Remove UID equality operator overrides

---

doc/whatsnew/v1.2.0.rst
pydicom/config.py
pydicom/dataset.py
pydicom/pixel_data_handlers/gdcm_handler.py
pydicom/pixel_data_handlers/jpeg_ls_handler.py
pydicom/pixel_data_handlers/numpy_handler.py
pydicom/pixel_data_handlers/pillow_handler.py
pydicom/pixel_data_handlers/rle_handler.py
pydicom/tests/test_JPEG_LS_transfer_syntax.py
pydicom/tests/test_dataset.py
pydicom/tests/test_gdcm_pixel_data.py
pydicom/tests/test_jpeg_ls_pixel_data.py
pydicom/tests/test_numpy_pixel_data.py
pydicom/tests/test_pillow_pixel_data.py
pydicom/tests/test_rle_pixel_data.py

Closes #578
Better exception messages for the handlers
* If no handlers support the transfer syntax, `NotImplementedError`
* If handlers support syntax but dependencies not met, `RuntimeError` and msg with handler name and required (unmet) dependencies.

[MRG+1] Better pixel data handler exceptions

---

.travis.yml
build_tools/travis/install.sh
pydicom/pixel_data_handlers/numpy_handler.py
pydicom/tests/test_environment.py

* Adds tests that confirm the TravisCI build environments are as expected.
* Fix pillow 'both' not installing with openjpeg (and hence no tests with jp2k plugin were running)
* Remove GDCM tests with python3.7 ([no installer available](https://anaconda.org/conda-forge/gdcm/files) for that version, builds were using 3.6 instead)
* Reorder builds so pypy runs first (workaround for #732)
* Use numpy with PyPy2 instead of numpypy
* Remove numpypy specific workaround from numpy handler

[MRG+1] Add tests for TravisCI build environment

---

pydicom/multival.py

Closes #740 
Changes `MutableSequence` import to from `collections.abc` (required for python 3.8+) while maintaining backwards compatibility.

[MRG+1] Import MutableSequence from collections.abc

---

doc/whatsnew/v1.2.0.rst
pydicom/pixel_data_handlers/gdcm_handler.py
pydicom/pixel_data_handlers/jpeg_ls_handler.py
pydicom/pixel_data_handlers/numpy_handler.py
pydicom/pixel_data_handlers/pillow_handler.py
pydicom/tests/test_gdcm_pixel_data.py
pydicom/tests/test_jpeg_ls_pixel_data.py
pydicom/tests/test_numpy_pixel_data.py
pydicom/tests/test_pillow_pixel_data.py
pydicom/tests/test_rle_pixel_data.py

Closes #717 
* Ensure pixel data handlers return writeable arrays by default
* Adds tests for writeability
Original array writeabilities:
* Numpy handler arrays with  BitsAllocated = 1 are writeable
* Numpy handler arrays with BitsAllocated > 1 are read-only
* RLE handler arrays are writeable (except with numpypy)
* Pillow handler arrays are writeable
* JPEG-LS handler arrays with NumberOfFrames = 1 are read-only
* JPEG-LS handler arrays with NumberOfFrames > 1 are writable
* GDCM handler arrays are read-only

[MRG+1] Make returned pixel data writeable, add tests

---

doc/whatsnew/v1.2.0.rst
pydicom/charset.py
pydicom/dataset.py
pydicom/filewriter.py
pydicom/tests/test_charset.py
pydicom/tests/test_filewriter.py
pydicom/valuerep.py
pydicom/values.py

- added warnings for encode/decode errors and incorrect encodings
- fixed writing of text VRs with multiple encodings
- fixes #716
This shall fix the encoding of person names and text.
* Encoding of person names with different encodings
* Encoding of text with multiple encodings
* Errors during encoding/decoding are now handled differently: a warning is logged, and the string is encoded/decoded with the default encoding using replacement characters (before it was tried to decode with different VRs like US, SS instead)
* PersonName3 behaves slightly differently:
* the different components accessors are now read-only
* decoding is done on demand only
* the original string is used for encoding if possible 
This got a bit larger than planned, but it is the final PR for #716.

[MRG+2] Added correct writing of PN values with multiple encodings

---

pydicom/filewriter.py
pydicom/tests/test_filewriter.py

- the argument did not make sense - writing raw bytes and reading
them back does not involve encoding
Took me some time to understand that this is not a bug...

[MRG+1] Removed superfluous encoding argument in tests

---

pydicom/tests/test_filewriter.py
pydicom/valuerep.py

- ensures that the default encoding is not set as the encoding if not known
- implies that decoding is called with the correct encodings
This fixes the warning (found by @darcymason in #733) that was triggered by setting the encoding of `PersonName3` to default encoding, if none was given, which always happens if creating a `DataElement` with a PN value manually and accessing it afterwards (see also the discussion in #751).
I couldn't find a scenario where this caused a real error (apart from the incorrect warning), so I tested only for the warning not issued, but there may be some case which I overlooked.

[MRG+1] Handle no encoding argument in PersonName3 as unknown encoding

---

pydicom/config.py
pydicom/dataelem.py
pydicom/tests/test_dataelem.py
pydicom/tests/test_dataset.py
pydicom/uid.py

Removes deprecated `uid` variables, `config.image_handlers` and `DeferredDataElement`

[MRG+1] Remove deprecated variables/class

---

doc/base_element.rst
doc/whatsnew/v1.3.0.rst
pydicom/dataset.py
pydicom/filereader.py
pydicom/tests/test_dataset.py

- fixes side effects from initializing with another dataset
- fixes #765
The reason for the problem was that if initialializing a dataset with another dataset, `__getitem__` was called for each contained element in the new Python versions (I didn't dig into the reasons why this has changed). This had some side effects, like converting all raw data elements (which was not wanted) and reading deferred values (which did not work as a file data set is assumed). Also the encoding was not correctly initialized.
I first tried to fix these problems, but found that it is easier not to derive from `dict` to fix this consistently.
I also thought about deriving from `UserDict` or `MutableMapping`, but didn't see any advantage for these - maybe I overlooked something.
I tried to make the change with …

[MRG] Do not derive Dataset from dict

---

pydicom/tests/test_valuerep.py

- fixes #771 
I'm still not sure why that happens in that build (it would happen if the test would have been executed twice), but setting global variables back after a test is always a good idea.

[MRG] Make sure that the retry order config is reset in the test

---

doc/whatsnew/v1.3.0.rst
pydicom/filewriter.py
pydicom/tests/test_filewriter.py

- can happen with values larger than 64kB in explicit transfer syntax
- closes #757

[MRG] Raise a specific exception if value is too large to be written

---

doc/whatsnew/v1.3.0.rst
pydicom/dataelem.py
pydicom/dicomdir.py
pydicom/filebase.py
pydicom/filereader.py
pydicom/pixel_data_handlers/gdcm_handler.py
pydicom/pixel_data_handlers/jpeg_ls_handler.py
pydicom/pixel_data_handlers/numpy_handler.py
pydicom/tests/test_dataelem.py
pydicom/uid.py

- removed dataelem functions isMultiValue, isStringOrStringList and isString
- also fixed a few warnings
- see #773

[MRG+1] Removed unused functions

---

pydicom/dataset.py
pydicom/filereader.py
pydicom/tests/test_dataset.py

Related to #779 
* Implement missing `dict` methods:
* `Dataset.items()`
* `Dataset.itervalues()`, `Dataset.iterkeys()`, `Dataset.iteritems()` in Python 2
* Rename `Dataset.tags` to `Dataset._dict`

[MRG+1] Add missing methods to Dataset, change Dataset.tags to Dataset._dict

---

pydicom/filewriter.py
pydicom/tests/test_filewriter.py

#781
Ensures ambiguous VR correction applied on saving newly created datasets.

[MRG] Fix ambiguous VR correction not being used

---

doc/whatsnew/v1.3.0.rst
pydicom/tests/test_valuerep.py
pydicom/valuerep.py

- made PersonName classes immutable by using tuples instead
of lists for components and encodings
- fixes #784

[MRG+1] Changed hash for PersonName3 to behave as expected

---

build_tools/travis/install.sh

- fixes #794 by avoiding to use the affexted NumPy version 1.16 in PyPy

[MRG] Use fixed NumPy version for PyPy to avoid PyPy bug

---

pydicom/dataelem.py
pydicom/tests/test_filereader.py
pydicom/values.py

Closes #791
Prints hex values rather than ASCII when the VR value hasn't been encoded in the alphabet range of ASCII values.
Looks like the PyPy + numpy environments in Travis are failing.

[MRG+1] Fix unknown VR exception message when VR isn't ASCII

---

doc/whatsnew/v1.3.0.rst
pydicom/tests/test_uid.py
pydicom/uid.py

Closes #788
If `generate_uid(None)` then use the integer form of a UUID v4 to create the UID instead of a combination of UUID v1 and hashing.

[MRG] Fix generate_uid(None) producing non-conformant UIDs

---

doc/whatsnew/v1.3.0.rst
pydicom/datadict.py
pydicom/tests/test_dictionary.py

- datadict.add_dict_entry and datadict.add_dict_entries now raise if
trying to add a private tag
- the new methods datadict.add_private_dict_entry/add_private_dict_entries
likely raise if trying to add non-private entries
- see #799

[MRG] Added possibility to add tags to the private dictionary

---

doc/whatsnew/v1.3.0.rst
pydicom/filereader.py
pydicom/tests/test_filereader.py

- fixes #810
This is the easy fix as proposed by the author of the issue.

[MRG+1] Do not try to seek back in an empty file

---

doc/whatsnew/v1.3.0.rst
pydicom/dataset.py
pydicom/filewriter.py
pydicom/sequence.py
pydicom/tests/test_filewriter.py

- set the parent dataset in sequences and sequence items
- use the parent dataset to access top-level tags
- fixes #804
I'm not really happy with this solution, but couldn't come up with a better one so far.
Fixing the writing was easier, but the reading part (which was the original issue) is a bit less straightforward.
Note that the issue has been seen elsewhere (while receiving and reading Little Endian datasets via pynetdicom), so I think this has to be fixed. If someone has a better idea though...

[MRG] Added handling of ambiguous tags in a sequence item

---

doc/whatsnew/v1.3.0.rst
pydicom/tag.py
pydicom/tests/test_tag.py

We've pointed people to `pydicom.datadict.tag_for_keyword` several times recently.  It occurred to me that tag creation by keyword could easily be added to the Tag class.
This allows, e.g.:
```python
>>> from pydicom.tag import Tag
>>> Tag("WaveformData")
(5400, 1010)
```

Add option to create Tag instances by DICOM keyword

---

doc/whatsnew/v1.3.0.rst
pydicom/filereader.py
pydicom/tests/test_filereader.py

- if the expected representation do not match the used one, a warning
is issued, or an exception raised if config.enforce_valid_values is set
- see #819 and #820

[MRG+1] Check really used implicit/explicit VR before reading a data set

---

doc/whatsnew/v1.3.0.rst
pydicom/charset.py
pydicom/tests/test_charset.py

- only raise if config.enforce_valid_values is set
- fixes #815

[MRG] Replace invalid encoding by default encoding

---

doc/whatsnew/v1.3.0.rst
pydicom/filewriter.py
pydicom/tests/test_filewriter.py

- do not raise while resolving an ambiguous VR
dependent on `PixelRepresentation` if both `PixelRepresentation`
and `PixelData` are not present
- closes #838
Note that I didn't issue a warning in this case intentionally, as the actual warning should be that the given tag is not used (or not expected) here. As we generally do not warn about this kind of situations (and this would come up only in the case of ImplicitVR) I think no warning is needed here.

[MRG] Do not raise on unneeded tags with ambiguous VR

---

pydicom/data/test_files/README.txt

The README.txt file in the test data directory lists `test_SR.dcm` as an example file, but in fact the file is called `test-SR.dcm` (NB hyphen vs underscore). This is a potential cause of minor confusion for users and developers.
This single-character change fixes this to make the README consistent with the actual filename

Typo in test_data/README.txt test_SR.dcm -> test-SR.dcm

---

pydicom/dicomdir.py

This pull request fixes a bug in the DicomDir init method that always sets is_implict_VR and is_little_endian to True. This causes errors when saving a DicomDir and loading the new file, as discussed in #9 and [here](https://groups.google.com/forum/#!topic/pydicom/DVeqyvXxpzU).

[MRG+1] Fix bug causing errors when loading from saved DicomDir

---

doc/whatsnew/v1.3.0.rst
pydicom/charset.py
pydicom/tests/test_charset.py

- the encodings are checked and replaced one by one
- invalid encodings are not handled as Python encodings,
if they are not valid encodings
- all invalid encodings are replaced by standard encoding
if config.enforce_valid_values is not set
- see #850

[MRG] Changed handling of invalid encodings for multi-value encodings

---

doc/whatsnew/v1.3.0.rst
pydicom/pixel_data_handlers/numpy_handler.py
pydicom/tests/test_numpy_pixel_data.py

- issue a warning if padding is missing
- closes #864

Allow missing padding byte in pixel data

---

appveyor.yml
build_tools/travis/install.sh

- do not upgrade conda in Travis.CI build
- do not upgrade installed setuptools in the AppVeyor build
- see #871
Note: I did not find the root cause of the problems, so this is only a workaround.
I reported [an issue](https://github.com/conda/conda/issues/8859), though I'm not sure if it's a problem with conda itself, or a packaging problem with miniconda/anaconda.

Workaround for build problems with conda 4.7.5

---

pydicom/charset.py
pydicom/tests/test_charset.py

In the original implementation, Pydicom use handled encoders such as shift_jis and iso-2022-jp if Japanese characters are given. But I found two issues as followings.
* shift_jis encoding doesn’t raise UnicodeError when characters which are out of JIS X 0201 are given.
* The escape sequence of starting ASCII code in iso-2022-jp encoding is fixed to ESC(B. But it should depend on value 1 of SpecificCharacterSet. For example, If ISO 2022 IR 13 is assigned to value 1 of SpecificCharacterSet, we should use ESC(J as an escape sequence of starting ASCII.
Closes #856
* Use custom encoders if ISO 2022 IR 13 and ISO 2022 IR 87 are given in SpecificCharacterSet.
* Use single byte output of shift_jis encoder to encode to jis-x-0201 in a custom encoder for ISO 2022 IR 13.
* Trim a tail escape …

[MRG] Fix jis-x-0201 characters encoding (#856)

---

doc/getting_started.rst
pydicom/__init__.py
setup.py

Deprecation warning for Python 2 support ending after v1.4.  Pytest<5 in setup.py if in Python2.
In my local setup, the `python setup.py test` did not work under Python 2.  It appeared to install pytest, but then later came up with an ImportError for pytest.  Tried many things, could not resolve, so added line to Testing section of Getting Started to instruct direct install of pytest<5 if needed.

Deprecation warning for Python 2; pytest<5

---

pydicom/dataelem.py
pydicom/tests/test_dataelem.py
pydicom/tests/test_dataset.py

Fixes #666 
Some `DataElement`s have a large `str` representation ATM, this applies trimming more thoroughly.

Fixed #666 (DataElement with huge str).

---

doc/whatsnew/v1.4.0.rst
pydicom/dataelem.py
pydicom/dataset.py
pydicom/tests/test_dataset.py
pydicom/tests/test_json.py

- expect bytes-like object instead of string
- fixed error handling in Dataset.from_json
- fixes #887
Note that this fixes just this issue - I haven't looked much further for similar problems yet.

[MRG] Fixed handling of binary values in json encoding

---

doc/whatsnew/v1.4.0.rst
pydicom/dataelem.py
pydicom/multival.py
pydicom/tests/test_dataelem.py
pydicom/tests/test_multival.py
pydicom/valuerep.py

- setting a UI value to None no longer raises, fixes #894
- fixed string output for numerical multi-values, fixes #892
- empty PN value now tests to False in Python 3, fixes #891
This is a stripped-down version of #895 which only fixes the mentioned issues - I removed all the `None`/empty value handling stuff discussed separately in #896, as suggested by @scaramallion.

Fixed some empty value handling issues

---

pydicom/config.py
pydicom/tests/test_config.py

Closes #611
Default logging configuration switched to `NullHandler`, changed `config.debug()` to add `StreamHandler` and use it by default.

[MRG] Use standard logging config as default

---

doc/whatsnew/v1.4.0.rst
pydicom/dataelem.py
pydicom/tests/test_dataelem.py

- fixes #899
This is a small fix which only targets known tags with VR UN - I didn't wante it to have any other impact. 
If the tag has another non-standard VR, it will be used as before.

[MRG] Correcly handle known tags with VR UN

---

pydicom/dataelem.py
pydicom/dataset.py
pydicom/jsonrep.py

- removed duplicate constants and methods
- moved Dataset._data_element_to_json to DataElement.to_json
- closes #889
Note that this is only a minor restructuring, I didn't change anything or add any tests. I noticed that there are several todos left, also some arguments not used yet.
@pieper - could you please review these changes, and maybe write a new issue with the tasks that still remain to do?

[MRG] Minor consolidation of json conversion code

---

doc/whatsnew/v1.4.0.rst
pydicom/filewriter.py
pydicom/tests/test_filewriter.py

- VR is replaced by UN in this case, as defined in PS3.5, 6.2.2
- fixes #757
See [discussion](https://github.com/pydicom/pydicom/pull/900#issuecomment-515681882) in #900.

[MRG] Fixed handling of data too large to be written in explicit transfer syntax

---

build_tools/travis/install.sh

- use the current conda version again
- see https://docs.conda.io/projects/conda/en/latest/user-guide/configuration/free-channel.html
- see #871
This is probably sufficient for now to handle #871. We can remove the free channel this later if not needed anymore.

[MRG] Re-add the free channel for conda, as we still need it

---

appveyor.yml

- re-added conda update
- free channel only needed for Python 2.7, as the
other older Python versions come with an older conda version
- closes #871
I forgot the AppVeyor build in the last PR (or rather wasn't aware that it could be solved the same way).
This is sufficient as long as the problematic Python versions are still supported, so I would close the related issue.

[MRG] Added free conda channel for appveyor builds

---

doc/old/python2_support.rst

Updates for latest discussion:
- Python 2 dropped in pydicom v2.0
- dropping Python 3.4 in v1.4

[MRG] DOC: update Python 2 support info

---

doc/reference/elem.dataelem.rst
pydicom/charset.py
pydicom/datadict.py
pydicom/dataelem.py
pydicom/dataset.py
pydicom/tests/test_charset.py
pydicom/tests/test_filereader.py

* Removes deprecated functions `dataelem.isMultiValue()` and `datadict.tag_for_name()`
* Removed `dataset.PropertyError` which hasn't been used [since 2017](https://github.com/pydicom/pydicom/commit/428ec344d1110da7a336cc412f6bd8a3d2af591e)
* Renamed `charset.decode()` to `decode_element()` and deprecated `charset.decode()` for removal in v1.5
* Changed a filereader test to capture the character set warning.

[MRG] Remove deprecated functions

---

doc/release_notes/v1.4.0.rst
pydicom/charset.py
pydicom/config.py
pydicom/dataelem.py
pydicom/dataset.py
pydicom/filereader.py
pydicom/filewriter.py
pydicom/tests/test_dataelem.py
pydicom/tests/test_filereader.py
pydicom/tests/test_numpy_pixel_data.py
pydicom/tests/test_rle_pixel_data.py
pydicom/tests/test_valuerep.py
pydicom/valuerep.py
pydicom/values.py

- setting a value to None or an empty string now always results
in an empty tag (VM = 0); see #896
This was a bit more tricky than I thought, and I'm not sure if this is the best way to implement this.
Also I'm not sure if this may cause some compatibility issues...
Anyway, I'm posting this as a discussion base, maybe someone has some better ideas.
Ping @scaramallion, @darcymason

[MRG] Fixed assigning of empty values to data elements

---

examples/dicomtree.py

Scrolling with the mouse wheel was not possible in the DICOM tree window. With a oneliner, this capability has been added. Window geometry has been also made slightly bigger.

[MRG] add the capability of scrolling with mouse wheel

---

doc/release_notes/v1.4.0.rst
pydicom/dataelem.py
pydicom/jsonrep.py
pydicom/tests/test_json.py
pydicom/valuerep.py

- fixed handling of single-valued elements
- fixed handling of VR PN and AT (AT is handled as binary)
- fixed handling of empty values
- fixes #915
I actually introduced the bug with the last change related to empty values, though after writing a test for it, I found a couple of more bugs. This PR has the following changes:
- single values are no more represented as lists after `from_json` (they are still represented as list in json though), so that they now match the representation before encoding
- all parts of person names are now encoded / decoded (only one part had been encoded)
- VR AT is now handled as a binary - have to check if this is the correct way to do this, but now the round-trip test passes
- empty values are set to the configured value

[MRG] Fixed some problems with json encoding/decoding

---

.travis.yml
build_tools/travis/install.sh

After successful builds the codecov upload intermittently fails.
This PR switches from using the codecov python uploader to the [bash one](https://docs.codecov.io/docs/about-the-codecov-bash-uploader) as recommended [here](https://community.codecov.io/t/unreliable-coverage-report-uploads/322/3)
Upload failures seem to have gone from about 5/37 to 0

[MRG] Fix issues with coverage report uploading failures

---

.codecov.yml
.travis.yml

Still getting about 1-2 upload failures every 74 builds due to failure to download the codecov bash script (curl timeout).
OK, 0 upload failures in 148 builds... now have to figure out why the reports [aren't being merged properly](https://codecov.io/gh/pydicom/pydicom/src/2c65dc6b0189bc7598105dbfc6a371f38c0a9569/pydicom/__init__.py#L51)
* Drops the curl timeout to 10 s from 120 s so timeouts trigger a retry faster
* Add 10 (x2) retry attempts

[MRG] Improve codecov upload robustness

---

doc/release_notes/v1.4.0.rst
pydicom/dataset.py
pydicom/filereader.py
pydicom/tests/test_filereader.py

- closes #932
This is a small change, basically using the `filename` argument to pass the file-like to be able to use it for deferred reading.

[MRG] Added support for deferred reading in file-like objects

---

pydicom/tests/test_valuerep.py
pydicom/valuerep.py

Closes #937
Python 3.8 removes `__str__()` from `int` and `float` which instead now call `object.__str__()` which itself defaults to `object.__repr__()`.
`DSfloat.__str__()`, `DSfloat.__repr__()` and `IS.__repr__()` all call the parent class' `__str__()` which calls the subclass' `__repr__()` method and so on, which causes a recursion error.
This PR:
* Fixes `DSfloat.__str__()` by creating a calling repr() instead and removing the `"` marks.
* Fixes `DSfloat.__repr__()` by calling the parent class' `__repr__()` instead of `str()`
* Fixes `IS.__repr__()` by implementing `IS.__str__()` in a similar manner to `DSfloat.__str__()` and making `IS.__repr__()` symmetric with `DSfloat.__repr__()`
See also: https://bugs.python.org/issue36793

[MRG] Compatibility fix for Python3.8

---

doc/release_notes/v1.4.0.rst
pydicom/tests/test_values.py
pydicom/valuerep.py
pydicom/values.py

- closes #940
A trailing zero had been tolerated for multi-values before, but not for single text values.
Now both single and multi-values tolerate multiple blank or zero endings without a warning (no warning was issued before - I left this for simplicity and to avoid more checks).

[MRG] Tolerate text values ending with multiple blanks or zero bytes

---

doc/release_notes/v1.4.0.rst
pydicom/dataelem.py
pydicom/multival.py
pydicom/tests/test_dataset.py

Mostly fixes #951 by passing the conversion function directly to `MultiValue` instead of a lambda function.
* Updating an unpickled multivalued element in Python 2 will raise an AttributeError due to `MultiValue.type_constructor` being missing. Can be worked around by doing `ds.Keyword = ds.Keyword` first. This only affects elements with VM > 1 ~that have been modified prior to pickling~.
```python
ds = dcmread(...)
ds.PixelSpacing = [1, 1]
pickle.dumps(ds, ...)
ds = pickle.load(...)
ds.PixelSpacing.insert(1, 2)
ds.PixelSpacing = ds.PixelSpacing
```

[MRG] Fix pickling modified datasets

---

doc/release_notes/v1.4.0.rst
pydicom/dataelem.py
pydicom/pixel_data_handlers/util.py
pydicom/tests/test_filereader.py
pydicom/tests/test_handler_util.py

Closes #942 by updating the value of the related elements during conversion to `DataElement` for values read from file.

[MRG] Fix incorrect first value for LUT elements

---

pydicom/pixel_data_handlers/pillow_handler.py
pydicom/tests/test_pillow_pixel_data.py

Related to #957, remove try/except blocks from the pillow decompression code so that exceptions are raised properly (and caught by `Dataset.convert_pixel_data()`). This will prevent useless tracebacks like:
```
~/anaconda3/lib/python3.7/site-packages/pydicom/pixel_data_handlers/pillow_handler.py in get_pixeldata(dicom_dataset)
197                 decompressed_image = Image.open(fio)
198             except IOError as e:
--> 199                 raise NotImplementedError(e.strerror)
200             UncompressedPixelData.extend(decompressed_image.tobytes())
201     except Exception:
NotImplementedError: None
```
I also refactored the code to simplify it.

[MRG] Remove try/except from pillow handler

---

pydicom/config.py
pydicom/dataelem.py
pydicom/tests/test_dataelem.py

- fixes #964, see #896
This changes the behavior of empty values for sequence tags (using `[]` instead of `None`), which had been discussed in #896, though with no clear conclusion, as far as I can see.
Please check if this is the wanted behavior.
Note that I didn't add an entry in the release notes, as this is probably covered by the entry for #896.

[MRG] Represent empty sequence as empty list instead of None

---

doc/release_notes/v1.4.0.rst
pydicom/dataset.py
pydicom/tests/test_json.py

- Dataset.from_json had ignored the bulk_data_element argument
- see #971
The issue will be closed only after it is clarified if we need some additional handling.

[MRG] Propagate bulk data handler to data element

---

.travis.yml
appveyor.yml

- added Python 3.7 to Appveyor builds
- removed Python 3.4 from both builds
I did this actually to reproduce #973, but it ~seems not to be reproducible with the CI test system~ is already fixed in master.
Thought it makes sense to merge this anyway, as 3.8 is out and we don't support 3.4 in the next pydicom version. Note that there is no gdcm version for this yet.

[MRG] Added Python 3.8 to Travis builds

---

examples/input_output/plot_read_dicom_directory.py
pydicom/data/__init__.py
pydicom/data/data_manager.py
pydicom/tests/test_data_manager.py
pydicom/tests/test_dicomdir.py

- convenience if you only need one file
- avoids problems with more than one file matching a pattern
This shall fix the Circle.CI problem, and I think it makes sense to have a function for a single test file, as this what we need in most cases.
I forgot that `get_testdata_files` puts an asterix around the pattern...

[MRG] Added function to get the path of a single test data file

---

doc/release_notes/v1.4.0.rst
pydicom/dataset.py
pydicom/tests/test_gdcm_pixel_data.py
pydicom/tests/test_jpeg_ls_pixel_data.py
pydicom/tests/test_numpy_pixel_data.py
pydicom/tests/test_pillow_pixel_data.py
pydicom/tests/test_rle_pixel_data.py

- also added it to Dataset.convert_pixel_data()
- see #537
Note: 
- I added a couple of tests only to one handler (the RLE handler), just to test the new argument. The actual functionality is already tested with each handler tests.
- you can only set one handler, not a list - I think this is sufficient
- no special error handling has been added if that handler fails, it uses the same messages as for the default handlers - not sure if this is sufficient

[MRG] Added optional handler argument to Dataset.decompress()

---

doc/old/image_data_handlers.rst
doc/old/working_with_pixel_data.rst
doc/release_notes/v1.4.0.rst
pydicom/pixel_data_handlers/pillow_handler.py
pydicom/tests/test_pillow_pixel_data.py

* Pixel data with Photometric Interpretation of YBR_FULL and YBR_FULL_422 no longer decoded as RGB (closes #273, closes #263)
Docs for [Image.draft()](https://pillow.readthedocs.io/en/stable/reference/Image.html#PIL.Image.Image.draft)
Documentation preview [here](https://1708-14006067-gh.circle-artifacts.com/0/home/circleci/project/doc/_build/html/index.html)

[MRG] Fix Pillow handler converting YBR to RGB

---

doc/release_notes/v1.4.0.rst
pydicom/dataset.py
pydicom/filewriter.py
pydicom/sequence.py
pydicom/tests/test_filewriter.py

- use a weakref as backlink to the dataset
- moved setting parent to `__getitem__` where it is always used
- added tests that fail without these changes
- fixes #994

[MRG] Avoid reference cycle in sequences

---

doc/release_notes/v1.4.0.rst
pydicom/dataset.py
pydicom/encaps.py
pydicom/filewriter.py
pydicom/pixel_data_handlers/pillow_handler.py
pydicom/tests/test_dataset.py
pydicom/tests/test_dicomdir.py
pydicom/tests/test_filewriter.py
pydicom/tests/test_json.py

* Sets `PixelData.is_undefined_length` implicitly during saving based on the transfer syntax compression when possible (closes #1006)
* Reverts the warning from #1008 in favour of a better exception message
* Sets `Dataset.is_implicit_VR` and `Dataset.is_little_endian` automatically from transfer syntax when possible and they're unset
* Added test of `shift` to pillow handler to save on array operation (maybe)
* Docstring updates, test updates to capture warnings
Documentation preview [here](https://1763-14006067-gh.circle-artifacts.com/0/home/circleci/project/doc/_build/html/index.html)

[MRG] Implicitly set PixelData.is_undefined_length when saving

---

doc/release_notes/index.rst
doc/release_notes/v1.4.1.rst
pydicom/dataelem.py
pydicom/tests/test_filewriter.py

- consider raw mode for empty sequence value
- fixes #1030
Note: I added release notes for 1.4.1 under the assumption that we will need a patch release, as this is a severe regression.

[MRG] Fixed writing of empty sequence

---

doc/release_notes/v1.4.1.rst
doc/tutorials/dicom_json.rst
doc/tutorials/index.rst
pydicom/dataelem.py
pydicom/dataset.py
pydicom/tests/test_json.py

- do not use bulk_data_threshold if no handler is given
- added basic documentation of JSON support
- closes #1029

[MRG] Changed bulk_data_threshold default to 1024

---

doc/release_notes/v2.0.0.rst
pydicom/data/data_manager.py
pydicom/dataset.py
pydicom/dicomdir.py
pydicom/filereader.py
pydicom/fileutil.py
pydicom/filewriter.py
pydicom/tests/test_filereader.py
pydicom/tests/test_fileutil.py
pydicom/tests/test_filewriter.py

- can be used dcmread, dcmwrite and Dataset.save_as
- closes #1047
This should handle any PathLike object for Python >= 3.6, not only `pathlib.Path`.

[MRG] Added support for PathLike filename arguments

---

doc/release_notes/v2.0.0.rst
pydicom/dataset.py
pydicom/filewriter.py
pydicom/tests/test_dataset.py

Fix for #1042.  Makes `save_as` a pure wrapper for `dcmwrite`.  Checks within save_as were folded into `dcmwrite`.
- Unit tests - no new ones, but existing are passing

[MRG] Common write

---

setup.cfg

- we do not support Python 2, so the wheels should not be found under Python 2
I ran into this issue with another Python 3-only-package, that could be installed under Python 2 due to this flag. To be sure not to forget this...

[MRG] Do not build universal wheels

---

doc/release_notes/v2.0.0.rst
pydicom/filewriter.py
pydicom/tests/test_filereader.py
pydicom/tests/test_filewriter.py
pydicom/tests/test_values.py
pydicom/values.py

* Closes #1075
* Reading OF values now results in ``bytes``  consistent with the other O* elements.
* Writing OF values now works correctly

[MRG] Fix reading and writing elements with a VR of OF

---

doc/release_notes/v2.0.0.rst
pydicom/dataelem.py
pydicom/dataset.py
pydicom/filewriter.py
pydicom/tests/test_dataelem.py
pydicom/tests/test_dataset.py

- minor docstring fixes
- fixes #1082
Note: I fixed this only for using the private block API. The problem will still happen if you add private tags without the private creator manually. Fixing that would be a bit more expansive, and I decided to regard this as deprecated.

[MRG] Fixed description of newly added known private tag

---

doc/release_notes/v2.0.0.rst
pydicom/filereader.py
pydicom/filewriter.py
pydicom/tests/test_filewriter.py

Fixes #1086
* I do  not understand what's being asked of me. The CircleCI build passed. I can see that artifacts were uploaded, but cannot figure out how to view the index.html
I was unable to run the pillow tests, despite installing NUMPY. We'll see if the automatic checks pass. Code coverage for filewriter:
```
Name                                             Stmts   Miss Branch BrPart  Cover
----------------------------------------------------------------------------------
pydicom\filewriter.py                              371     28    210     16    91%
```
compared to master at
```
pydicom\filewriter.py                              357     28    206     15    91%
```
* No new pyflake warnings. Unused `tzinfo` in `test_filewriter.py` remains
* No new pep8 warnings. These exist in the …

[MRG] Write deflated content when called Transfer Syntax is Deflated Explicit VR Little Endian

---

doc/old/base_element.rst
doc/old/private_data_elements.rst
doc/reference/config.rst
doc/reference/dataset.rst
doc/release_notes/v2.0.0.rst
doc/tutorials/dataset_basics.rst
examples/input_output/plot_write_dicom.py
pydicom/benchmarks/bench_handler_numpy.py
pydicom/config.py
pydicom/dataset.py
pydicom/filereader.py
pydicom/tests/test_dataset.py
pydicom/tests/test_filereader.py
pydicom/tests/test_filewriter.py
pydicom/tests/test_handler_util.py
pydicom/tests/test_numpy_pixel_data.py
pydicom/tests/test_rle_pixel_data.py
pydicom/tests/test_util.py
pydicom/util/codify.py

We'd discussed in #881 about moving toward complete integration of file_meta into `Dataset`.  Another alternative is to mimic that by having a file_meta which is internally separate, but appears to be integrated. 
I had worked on this in #885, but was hitting some walls - it gets very tricky very quickly.  In this PR, I'm proposing a step in the right direction, that should make it easier to move forward later. There are some small behavior changes, so ideally this step should be taken for v2.0 release.
One problem in all this is that there is a lot of existing code such as:
```python
file_meta = Dataset()
ds.file_meta = file_meta
file_meta.TransferSyntaxUID = "1.2.3"
```
Note that the object _reference_ is assigned, but the file_meta data elements are added after that assignment. So the …

[MRG] New file meta

---

pydicom/_version.py

Slightly different naming than previously used for release candidate - trying to follow semver.org.  However, can go back to the previous style "2.0.0rc1" if there is some reason to - I just thought semver.org provides a clear grammar that's easy to point to.

Update version for v2.0.0-rc.1

---

doc/release_notes/v2.1.0.rst
pydicom/compat.py
pydicom/dataset.py
pydicom/fileutil.py
pydicom/sr/codedict.py
pydicom/tests/test_fileutil.py

* clean up some other Python 2 related code
- ~~[ ] Unit tests added that reproduce the issue or prove feature is working~~

[MRG] Remove Python 3.5 codes; warn on compat module

---

README.md

Zenodo did not trigger on creation of github release of pydicom 2.0 as expected.  With help from zenodo support, got it built and a DOI assigned.

Update zenodo DOI for v2.0 release

---

pydicom/sr/codedict.py

This is a faster and more idiomatic way of using `itertools.chain`. Instead of computing all the items in the iterable and storing them in memory, they are computed one-by-one and never stored as a huge list. This can save on both runtime and memory space.

Use chain.from_iterable in codedict.py

---

pydicom/filewriter.py
pydicom/tests/test_dataset.py
pydicom/tests/test_filewriter.py
pydicom/tests/test_handler_util.py

* Add test of encoding attributes when `write_dataset()` is called (related to #1062)
* Switch to f-strings
* Bit of a style cleanup

[MRG] Check is_little_endian and is_implicit_VR in write_dataset()

---

pydicom/sr/codedict.py

@darcymason Here's the refactoring. I did it mostly as a fun exercise.
I tested in manually on these inputs and it passed:
```
assert _filtered(('foo', 'bar', 'bazz', 'baz'), ()) == ['bar', 'baz', 'bazz', 'foo']
assert _filtered(('foo', 'bar', 'bazz', 'baz'), ('b', )) == ['bar', 'baz', 'bazz']
assert _filtered(('FOo', 'bar', 'bazz', 'baz'), ('ba', 'b', 'x')) == ['bar', 'baz', 'bazz']
assert _filtered(('fo', 'bar', 'bazz', 'baz'), ('ba', 'f')) == ['bar', 'baz', 'bazz', 'fo']
assert _filtered(('fOo', 'bar', 'bazz', 'baz'), ('FOO')) == ['fOo']
```

Refactor codedict._filtered

---

doc/release_notes/v2.1.0.rst
pydicom/dataset.py
pydicom/tests/test_dataset.py

- used method inherited from dict before, which always returned empty dict
- fixes #1146

[MRG] Added Dataset.copy() method

---

pydicom/uid.py

Add convenience constants for referencing MPEG family UIDs in code.

[WIP] feat: add convenience constants for MPEG transfer syntaxes

---

pydicom/pixel_data_handlers/gdcm_handler.py
pydicom/tests/test_gdcm_pixel_data.py

Closes #1153, if the dataset doesn't originate from file and in-memory decoding isn't available then write the pixel data and related elements to a temporary file and use that as the decoding source.

[MRG] Fix GDCM handler not working with BytesIO

---

doc/release_notes/v2.1.0.rst
pydicom/dataelem.py
pydicom/dataset.py
pydicom/tests/conftest.py
pydicom/tests/test_charset.py
pydicom/tests/test_dataelem.py
pydicom/tests/test_dataset.py
pydicom/tests/test_dicomdir.py
pydicom/tests/test_filereader.py
pydicom/tests/test_filewriter.py
pydicom/tests/test_gdcm_pixel_data.py
pydicom/tests/test_jpeg_ls_pixel_data.py
pydicom/tests/test_multival.py
pydicom/tests/test_numpy_pixel_data.py
pydicom/tests/test_overlay_np.py
pydicom/tests/test_rle_pixel_data.py
pydicom/tests/test_util.py
pydicom/tests/test_valuerep.py

- now issues a warning and set the VR to UN
- raises KeyError only if config.enforce_valid_values is set
- added and used conftest.py for common fixtures
- see #1161

[MRG] Change default handling for reading unknown tags

---

.github/workflows/master-push.yml

Now that the tests that utilise pydicom are within the released package, make it so that only production versions of pymedphys are tested by the master merge for pydicom

[RFR] Make pymedphys testing only install production versions

---

doc/release_notes/v2.1.0.rst
pydicom/filereader.py
pydicom/filewriter.py
pydicom/tests/test_filereader.py
pydicom/tests/test_filewriter.py

- raise if the filename / fp argument is None or not a str or file-like
This came up twice in Stackoveflow: someone tried to use `get_testdata_file` with  a local file, passed the result (which was `None`) into `dcmread` and got something like:
```
Traceback (most recent call last):
File "addfields.py", line 14, in <module>
ds = pydicom.dcmread(fn)
File "/Users/user/opt/anaconda3/lib/python3.7/site-packages/pydicom/filereader.py", line 871, in dcmread
force=force, specific_tags=specific_tags)
File "/Users/user/opt/anaconda3/lib/python3.7/site-packages/pydicom/filereader.py", line 668, in read_partial
preamble = read_preamble(fileobj, force)
File "/Users/user/opt/anaconda3/lib/python3.7/site-packages/pydicom/filereader.py", line 605, in read_preamble
preamble = fp.read(128)
AttributeError: …
```

[MRG] Raise TypeError if dcmread or dcmwrite is called with wrong argument

---

pydicom/pixel_data_handlers/util.py
pydicom/tests/test_handler_util.py

In certain DICOM images, the "Number of Frames" field exists but has a value of None. These images are not handled properly and throw an error.
Example DICOM contents:
_...
(0028, 0008) Number of Frames                    IS: None
..._

[MRG] Handle case where NumberOfFrames exists but is None

---

doc/release_notes/v2.1.0.rst
pydicom/pixel_data_handlers/util.py
pydicom/tests/test_handler_util.py

**Describe the issue**
Hello, we've been using 
```
img = apply_voi_lut(apply_modality_lut(dcm.pixel_array,dcm),dcm)
plt.imshow(img)
```
And it will crash if apply_modality_lut will return float (it returns float `if 'RescaleSlope' in ds and 'RescaleIntercept' in ds`)
**Expected behavior**
It should still work or at least handle error differently and say (you can only apply_vol_lut to integer values)
**Steps To Reproduce**
How to reproduce the issue. Please include:
1. Get dicom that satisfies condition `if 'RescaleSlope' in ds and 'RescaleIntercept' in ds`
2. 
```---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
in 
3 
4 # extracting image (pixels data)
----> 5 img = …
```

[MRG] Fix for dicom apply_voi_lut with float images

---

.github/workflows/master-push.yml

As of 0.33.0 all dependencies are classified as "optional". To install everything that might be needed to use pymedphys it now requires the `user` flag:
https://docs.pymedphys.com/release-notes.html#installation-changes
It should have twigged that this would mess up the pymedphys on-master push.
Thanks @darcymason for you patience with this one.

[MRG] Add 'user' extras to pymedphys install

---

doc/reference/config.rst
doc/release_notes/v2.1.0.rst
pydicom/config.py
pydicom/dataelem.py
pydicom/dataset.py
pydicom/tag.py
pydicom/tests/test_dataelem.py
pydicom/tests/test_dataset.py
pydicom/tests/test_tag.py

Closes #1215, related to #1214  
* Improve exceptions messages for `Tag()` and change a `ValueError` to a `TypeError`
* Raise `KeyError` with `ds['invalid']` instead of `ValueError`
* Add configurable behaviour (and warn instead of raising) for invalid keys used with the `in` operator: `'invalid' in ds`
* Fix `setdefault()` not working correctly for a value of `None` and with private tags
* Add `DataElement.is_private` property

[MRG] Improvements for Dataset's dict methods

---

pydicom/multival.py
pydicom/sequence.py
pydicom/tests/test_multival.py
pydicom/tests/test_sequence.py

* Add type hints for Sequence and MultiValue
* Add `append` and `insert` methods to Sequence so the `parent` attr is set correctly, fix `__setitem__` not working with slices.

[MRG] Add type hints for Sequence and MultiValue

---

doc/release_notes/v2.1.0.rst
pydicom/tests/test_valuerep.py
pydicom/valuerep.py

pydicom currently accepts floats for `IS` when `int(float_val) == float_val`. This PR allows conversion of floats that are represented as strings to `IS` when `int(float(str_val)) == float(str_val)`.

[MRG] Accept floats in strings (e.g. "1.0") for IS VR

---

doc/reference/encaps.rst
doc/release_notes/v2.1.0.rst
pydicom/encaps.py
pydicom/tests/test_encaps.py

* Closes #1178 
* Raise an exception if `encapsulate()` is used with to much frame data
* Add `encapsulate_extended()` helper function

[MRG] Add support for the Extended Offset Table

---

.github/workflows/release.yml
pydicom/_version.py

* build, test in venv, upload to PyPI
As discussed in #1130, adding workflow to trigger when github release created.
This was tested in a skeleton separate package and confirmed working. 
Builds `dist` (wheel and source dist), installs the package to venv, then uploads to PyPI if tests successful.
Based on @scaramallion's draft workflow [here](https://github.com/pydicom/pynetdicom/commit/bb22bb065a06e60b19499651f03c158be7d94cdb), but did not upload to TestPyPI first, since easy to install from local wheel instead, and avoids problem of needing to update `__version__` if tests failed after install from TestPyPI (same version cannot be re-uploaded even if deleted from TestPyPI).
- ~~[ ] Unit tests added that reproduce the issue or prove feature is working~~ Tested in private repo
- ~~[ ] …

Add release workflow

---

pydicom/jsonrep.py
pydicom/tests/test_json.py

- Ensured that the bulk_data_uri_handler is calledfor bulk data elements in SQ elements
- Added a test `test_bulk_data_reader_is_called_within_SQ` to test this use case
- Closes #1254

[MRG] Fix Sequences with Bulk Data  when loading from JSON fixes

---

doc/release_notes/index.rst
doc/release_notes/v2.1.1.rst
pydicom/_version.py
pydicom/filebase.py
pydicom/jsonrep.py
pydicom/tests/test_json.py
setup.py

* Version bump to 2.1.1
* Fix `ImportError` for Python 3.6.0, I checked the docs and this appears to be the only import that should be an issue
* Remove `py.typed`
* Fix JSON conversion error (backported from #1256)
* Closes #1251 and closes #1253

[MRG] Typing and JSON fixes

---

pydicom/filewriter.py

Adjustment after seeing duplicated text in the docs:
https://pydicom.github.io/pydicom/dev/reference/generated/pydicom.filewriter.dcmwrite.html#pydicom.filewriter.dcmwrite:~:text=If%20write_like_original%20is%20True%20then%20the,conformant%20with%20the%20DICOM%20File%20Format).

Remove duplicate text within `dcmwrite` docstring

---

doc/reference/config.rst
doc/release_notes/v2.2.0.rst
pydicom/config.py
pydicom/dataelem.py
pydicom/errors.py
pydicom/tests/test_dataelem.py
pydicom/values.py

Added UserWarning and fallback behavior when a byte string cannot be unpacked into a number due to invalid byte string length.
Private fields can have non-conformant behavior and result in errors while parsing. In my case, a field is supposed to be a double floating point (8 bytes) but the byte string only contains 6 bytes.
Example:
_...
(0019, 1027) Private tag data                    FD: b'15030 '
..._

[WIP] Added optional UserWarning and fallback behavior when a byte string cannot be unpacked into a number

---

doc/release_notes/index.rst
doc/release_notes/v2.1.2.rst
pydicom/_version.py
setup.py

* Change minimum Python version to 3.6.1
* Bump pydicom version to 2.1.2
* Add release notes for 2.1.2

[MRG] Change minimum supported Python version

---

doc/release_notes/v2.2.0.rst
pydicom/dataset.py
pydicom/sequence.py
pydicom/tests/test_dataset.py

- weakref is removed on pickling and re-added during unpickling
- fixes #1278
Just removing and re-adding the weakref seems to do the trick, and I couldn't find a scenario where it will not be set to the correct value afterwards, but I may have overlooked something.

[MRG] Fix pickling of weakref in Dataset and Sequence

---

pydicom/filereader.py

[MRG] Fix docstring for dcmread

---

doc/guides/element_value_types.rst
doc/release_notes/v2.2.0.rst
pydicom/dataelem.py
pydicom/tests/test_dataelem.py

I noticed a comment on the [Element VRs and types page](https://pydicom.github.io/pydicom/stable/guides/element_value_types.html) about having to be careful setting **AT** values, which seemed it should be unnecessary with this small change.  Also, the table had the stored value as `int`, rather than `BaseTag`, which is actually what is used when read from file (and will be guaranteed now with this change).
This PR checks for **AT** on setting a data element and converts using `Tag` so it will always be a `BaseTag` stored, and invalid `Tag` values will generate an error.  All forms accepted by `Tag`, including DICOM keywords, are accepted.

[MRG] Set values for VRs of AT using Tag()

---

pydicom/dataelem.py
pydicom/tests/test_dataelem.py

Fix for #1291, allowing valid 0x00000000 tag to be set.

[MRG] Properly convert (0000, 0000) AT tag

---

doc/release_notes/v2.2.0.rst
pydicom/dataelem.py
pydicom/tests/test_json.py

It is incorrect to check for presence of keys in a dictionary object using `hasattr`. This will always return `False` and thus will never run the numerical conversion.

[MRG] fix numerical json export bug

---

doc/release_notes/v2.2.0.rst
pydicom/filereader.py

Remove UserWarning when do implied switch to implicit VR; the need for this to be removed was noted in #1305. 
Also added line in release notes about the feature and config option (missing when it was originally introduced).

Remove warning for attempted switch to implicit VR

---

pydicom/dataset.py
pydicom/tests/test_json.py

Add an option to the `to_json` and `to_json_dict` methods for the dataset class that will catch the exception raised when a tag fails to be converted to a json dictionary, and drop the key from the result. An error level message is always logged.

[MRG] Add option to suppress exception and continue serialization

---

pydicom/tests/test_valuerep.py
pydicom/valuerep.py

Two alternative constructors for the `pydicom.valuerep.PersonName` attribute are added using classmethods: `PersonName.from_named_components()` and `PersonName.from_named_components_veterinary()`. The purpose of these is to allow users to construct person names correctly in a more intuitive way than is currently possible, without having to understand or implement the low level details about how the parts of names are ordered and joined together. Here is an example taken from the [examples](http://dicom.nema.org/dicom/2013/output/chtml/part05/sect_6.2.html#sect_6.2.1.1) in the DICOM standard:
```python
from pydicom.valuerep import PersonName
pn = PersonName('Adams^John Robert Quincy^^Rev.^B.A. M.Div.')
pn = PersonName.from_named_components(
family_name='Adams',
given_name='John Robert …
```

[MRG] Person Name Constructors

---

doc/reference/elem.valuerep.rst
doc/reference/index.rst
doc/release_notes/v2.2.0.rst
pydicom/tests/test_valuerep.py
pydicom/valuerep.py

As described in #1264, decimal strings (DS) must be 16 characters or fewer per the standard, but when using `DSfloat` pydicom will silently allow longer decimal strings even when `config.enforce_valid_values` is set to `True`. (There is an existing test for `DSdecimal`). Furthermore, though it is not mentioned in #1264, non-finite float values (`inf`, `nan`) can be silently stored as decimal strings even when `config.enforce_valid_values` is set to `True` even though this is also disallowed by the standard. This is also true for the non-finite values of `Decimal` (`Infinity` and `NaN`). There is also no functionality to allow users to format their DSs correctly, which I argue would be very useful for users as the process is not especially straightforward to do for arbitrary floats.
This …

[MRG] Check for invalid DSs and add function to correctly truncate

---

pydicom/tests/test_dataelem.py
pydicom/tests/test_dataset.py
pydicom/tests/test_valuerep.py
pydicom/valuerep.py

Fixes an unexpected behaviour with the recently introduced DS formatting (#1334).
While using the recently-merged functionality for automatic DS formatting, I found a problem wherein the `auto_format` attribute is not correctly copied when constructing a `DSfloat`/`DSdecimal` from another `DSfloat`/`DSdecimal`. Since this process occurs when using the attribute assignment syntax on `Dataset`, the result is that the following does not work as expected:
```python
from pydicom import Dataset
from pydicom.valuerep import DS
import math
dataset = Dataset()
dataset.PatientWeight = DS(math.pi, auto_format=True) 
print(dataset.PatientWeight)
```
I have now fixed this issue such that:
- When a `DSfloat`/`DSdecimal` is constructed from another `DSfloat`/`DSdecimal`, its `auto_format` attribute is …

[MRG] Copy auto_format attribute when constructing DS objects

---

.github/workflows/master-push.yml
.github/workflows/pythonpackage.yml
.github/workflows/release.yml
pydicom/pixel_data_handlers/pylibjpeg_handler.py
pydicom/pixel_data_handlers/util.py
pydicom/tests/test_pylibjpeg.py

* Updates for pylibjpeg changes (different import path, changed warning message)
* Capture warnings in pylibjpeg tests
* Use `float` rather than np.float due to [upcoming removal](https://numpy.org/doc/stable/release/1.20.0-notes.html#using-the-aliases-of-builtin-types-like-np-int-is-deprecated)
* Bump CI workflows to Python 3.9 now that it's supported by pylibjpeg

[MRG] Updates for pylibjpeg changes

---

doc/release_notes/v2.2.0.rst
pydicom/data/__init__.py
pydicom/data/data_manager.py
pydicom/tests/test_data_manager.py

- fixes exception while reading DICOM data if `setuptools` are not installed
- see #1341
This just makes the offending import of `pkg_resources` into a local import, and replaces the global variable that always loads the data sources on import with a function. As this code is seldom needed, I think this would be ok, not sure if it breaks any external code, though.

[MRG] Do not load external data sources until needed

---

doc/release_notes/v2.2.0.rst
pydicom/data/download.py
pydicom/data/retry.py
pydicom/env_info.py

it offers an additional solution (`requests`).
This is an issue discussed at https://github.com/pydicom/pydicom/issues/1333, implemented as follows.
In some network environments, `urllib` cannot download testfile as follows.
```
$ pytest -k test_dataset.py -s
=================================== test session starts ===================================
platform darwin -- Python 3.8.8, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /Users/youngkiu/src/pydicom
emri_small.dcm: 0.00B [00:00, ?B/s]
<urlopen error [Errno 54] Connection reset by peer>, Retrying in 3 seconds...
emri_small.dcm: 0.00B [00:00, ?B/s]
<urlopen error [Errno 54] Connection reset by peer>, Retrying in 6 seconds...
emri_small.dcm: 0.00B [00:00, ?B/s]
<urlopen error [Errno 54] Connection reset by peer>, Retrying in 12 …
```

[WIP] When the user encounters the problem of downloading the testfile,

---

pydicom/env_info.py
pydicom/tests/test_env_info.py

While creating issue https://github.com/pydicom/pydicom/issues/1346, I commit the updated `env_info.py`.
Now you know the installed version of all optional libraries. https://pydicom.github.io/pydicom/stable/tutorials/installation.html#install-the-optional-libraries
```
$ python -m pydicom.env_info
module       | version
------       | -------
platform     | macOS-10.16-x86_64-i386-64bit
Python       | 3.8.8 | packaged by conda-forge | (default, Feb 20 2021, 16:12:38)  [Clang 11.0.1 ]
pydicom      | 2.2.0.dev0
gdcm         | _module not found_
jpeg_ls      | _module not found_
numpy        | 1.20.2
PIL          | _module not found_
pylibjpeg    | 1.2.0
openjpeg     | 1.1.1
libjpeg      | 1.2.0
```

[MRG] Add pylibjpeg libraries and versions to the env_info output

---

pydicom/dataset.py
pydicom/tests/test_dataset.py

Better warning message when using the `Dataset.__contains__` operator

[MRG] Better message when invalid value used with the in operator

---

.github/workflows/master-push.yml
.github/workflows/pythonpackage.yml
doc/old/image_data_handlers.rst
doc/release_notes/v2.2.0.rst
doc/tutorials/installation.rst
pydicom/pixel_data_handlers/pylibjpeg_handler.py
pydicom/tests/test_pylibjpeg.py

Add support for RLE decoding (via pylibjpeg-rle plugin) to the pylibjpeg handler, generally about 4-5x faster than the default for real world data

[MRG] Add support for RLE to the pylibjpeg handler

---

doc/release_notes/v2.2.0.rst
pydicom/tests/test_filewriter.py
pydicom/tests/test_valuerep.py
pydicom/valuerep.py

- use original_string to save the DICOM-conform representation
- fixes #1262
Please check if this change would be ok now, or we need a configurable option, or shall defer the change until 3.0 (if we want to make it at all).

[MRG] Change representation of DA, DT and TM to be a DICOM-conform string

---

.github/workflows/pythonpackage.yml
pydicom/pixel_data_handlers/pylibjpeg_handler.py

pylibjpeg-rle v1.1 changes the byte order from big to little endian for returned decoded data. See also #1364

[MRG] Fix for pylibjpeg-rle changing byte order of returned data

---

doc/release_notes/v2.2.0.rst
pydicom/dataset.py
pydicom/tests/test_dataset.py
pydicom/tests/test_fileset.py
pydicom/tests/test_json.py

- avoids copying the filename which can be a file-like object
- fixes #1147

[MRG] Allow to deepcopy a FileDataset object

---

pydicom/tests/test_pylibjpeg.py

Trial fix for intermittently failing test:
```python
_________________________ TestRLEEncoding.test_encode __________________________
self = <pydicom.tests.test_pylibjpeg.TestRLEEncoding object at 0x7f6c4cd1acd0>
def test_encode(self):
"""Test encoding"""
ds = dcmread(EXPL)
assert 'PlanarConfiguration' not in ds
expected = get_expected_length(ds, 'bytes')
assert expected == len(ds.PixelData)
ref = ds.pixel_array
del ds.PixelData
ds.compress(RLELossless, ref, encoding_plugin='pylibjpeg')
assert expected > len(ds.PixelData)
assert np.array_equal(ref, ds.pixel_array)
>       assert id(ref) != id(ds.pixel_array)
E       AssertionError: assert 140103122488560 != 140103122488560
E        +  where 140103122488560 = id(array([[244, 244, 244, ..., 244, 244, 244],\n       [244, 244, 244, ..., 244, …
```

[MRG] Improve test robustness

---

.github/workflows/pr-typing.yml
pydicom/tests/test_util.py
pydicom/tests/test_valuerep.py
pydicom/valuerep.py

* Return `""` for `IS("")` rather than `None` (reverts change in #1213, should be consistent with all other elements except SQ)
* Change `repr` format to match Python
* Add `__eq__` and `__ne__` operators and allow string comparison
* Add `mypy.ini` and typing workflow for PRs
Closes #1398

[MRG] Fix IS returning None for empty str

---

doc/release_notes/v2.2.0.rst
pydicom/dataset.py
pydicom/encoders/base.py
pydicom/multival.py
pydicom/pixel_data_handlers/gdcm_handler.py
pydicom/pixel_data_handlers/pillow_handler.py
pydicom/pixel_data_handlers/pylibjpeg_handler.py
pydicom/pixel_data_handlers/rle_handler.py
pydicom/pixel_data_handlers/util.py
pydicom/sequence.py
pydicom/tests/test_dataset.py

* Change `Dataset` to no longer inherit from `dict`. Fixes a Liskov substitution issue and `__iter__` type hint problem
* Add `__array__` implementation so dataset access still works in a numpy array.
* Some minor type improvements
* Ensure `FileDataset.file_meta` exists and is not `None`
Missing `dict` methods:
* Python 3.6+: ``__class__,  __doc__, __hash__, fromkeys``
* Python 3.8+: ``__reversed__``
* Python 3.9+: ``__ior__, __or__, __ror__, __class_getitem__``

[MRG] Don't inherit Dataset from dict

---

doc/release_notes/v2.2.0.rst
pydicom/dataelem.py
pydicom/tests/test_valuerep.py

[MRG] Fix setting VR OL, OD and OV values containing backslashes

---

pydicom/tests/test_valuerep.py
pydicom/valuerep.py

It appears that a change in #1397 that changed the repr of DSfloat from being enclosed in double quotes to now being enclosed in single quotes. This change broke some checks on the representation of the `DSfloat` that are run in the `DSfloat` constructor when `pydicom.config.enforce_valid_values` is set to `True`. This has had some pretty severe consequences, for example the following snippet currently raises a `ValueError`:
```python
import pydicom
pydicom.config.enforce_valid_value = True
pydicom.valuerep.DSfloat(1.0)  # ValueError!
```
This pull request makes a simple tweak to fix this bug by stripping whatever outer characters surround the repr rather than stripping literal double quote characters. It also adds some regression tests simply by deploying the existing fixture to run …

[MRG] Fix DSfloat bug when enforce_valid_values is True 

---

pydicom/sr/coding.py
pydicom/tests/test_coding.py

This will allow using codes as dictionary keys!
Adds a `__hash__` method to `pydicom.sr.coding.Code` to allow instances to be included into a `set` and used as `dict` keys.
- [] Code typed and mypy shows no errors
- [] Unit tests passing and overall coverage the same or better

[MRG] Make codes hashable

---

doc/release_notes/v2.2.0.rst
pydicom/tests/test_charset.py
pydicom/valuerep.py

- typo in constant used for PN component delimiter while handling
code extensions
This is a bit embarassing - used `0xe5` instead of `0x5e` for `^`, and the single-byte encoding tests have not been made with PN, so they passed even though the byte data was incorrect. Noticed this while trying to port some of the tests to fo-dicom.

[MRG] Fix incorrect component delimiter constant

---

.github/workflows/master-push.yml

PyMedPhys released a development version ([0.38.0.dev0](https://pypi.org/project/pymedphys/0.38.0.dev0/)) containing a fix for https://github.com/pydicom/pydicom/pull/1458#issuecomment-893891181.
By making pydicom pull a development release this allows me to fix pydicom's CI promptly without needing to craft a production pymedphys release.

[MRG] Make workflow install --pre pymedphys release

---

doc/release_notes/v0.9.5.rst
doc/release_notes/v1.2.0.rst
doc/tutorials/filesets.rst
pydicom/dataset.py
pydicom/encoders/native.py
pydicom/filewriter.py
pydicom/pixel_data_handlers/util.py
pydicom/tests/test_handler_util.py

Fixes typos detected by [codespell](https://github.com/codespell-project/codespell).
I have very slightly modified a couple past release notes, I hope that's acceptable.

[MRG] Typos found by codespell

---

doc/tutorials/installation.rst

due to API changes you shall be using at least 1.1, otherwise, you have the lib installed, but from pylibjpeg.pydicom.utils import get_pixel_data_decoders is not valid

set pylibjpeg min version

---

pydicom/dataset.py

[MRG] Iterate through the value attribute

---

doc/release_notes/index.rst
doc/release_notes/v2.3.0.rst
pydicom/filewriter.py
pydicom/tests/test_filewriter.py

[MRG] Pad odd-length OB values during write

---

doc/old/image_data_compression.rst
doc/release_notes/v2.3.0.rst
pydicom/dataset.py
pydicom/filewriter.py
pydicom/tests/test_encoders.py
pydicom/tests/test_filewriter.py

* Closes #1565 
* Ensures dataset is encoded explicit VR little endian when using `Dataset.compress()`
* Adds a warning to `dcmwrite()` when the wrong encoding is used for encapsulated datasets

[MRG] Ensure encoding is correct when using Dataset.compress()

---

pydicom/values.py

Using `logger.warn` emits deprecation warnings in recent versions of Python.

[MRG] Prefer logger.warning to deprecated logger.warn

---

pydicom/benchmarks/bench_handler_numpy.py
pydicom/pixel_data_handlers/numpy_handler.py

* Improve efficiency of bit packing and unpacking
* `unpack_bits()` (time per 100 runs): 55.0 ms -> 6.0 ms
* `pack_bits()` (time per 100 runs): 63.6 ms -> 22.0 ms

[MRG] Improvements for bit packing and unpacking

---

doc/release_notes/v2.3.0.rst
pydicom/dataset.py
pydicom/tests/test_dataset.py

- always set filename and fileobj_type instance vars
- fixes #1571

[MRG] Fix AttributeError on deep copy of FileDataset

---

pydicom/tests/test_dataelem.py
pydicom/tests/test_valuerep.py
pydicom/valuerep.py

- fix for previous value validation commit
- as found by @scaramallion, empty string values were not allowed for some VRs

[MRG] Allow empty string values

---

doc/release_notes/v2.3.0.rst
pydicom/_private_dict.py

Incorporates fixes to
* HOLOGIC, Inc. 0019xx42
* MITRA LINKED ATTRIBUTES 1.0 0031xx20 (Global Patient ID)
Enhances several MITRA OBJECT UTF8 ATTRIBUTES 1.0 definitions.
Removes all MITRA MARKUP 1.0 definitions.

[MRG] Rebuild private dictionary from GDCM

---

pydicom/tests/test_dataelem.py
pydicom/uid.py
pydicom/valuerep.py

- byte strings had not been handled in regex validation
- add tests for direct calls of validate_value
This is an addon to PR #1543, see the discussion there.

[MRG] Make sure validate_value handles byte strings

---

doc/release_notes/v2.3.0.rst
pydicom/dataelem.py
pydicom/tests/test_json.py
pydicom/tests/test_valuerep.py

- is now handled like adding the single value in the list
- fixes #1606
Only handles the case of a list with a single value. I'm unsure if we also have to handle assigning an empty list, but as this seems to make no problems, and may potentially change the behavior, I left it out.

[MRG] Handle adding a list with one value

---

doc/release_notes/v2.3.0.rst
pydicom/filereader.py
pydicom/tests/test_filereader.py

Allow multiple deferred reads with file-like objects by ensuring that any file-like object is not unnecessarily closed. 
Closes #1609

[MRG] allow multiple deferred reads with file-like objects

---

examples/input_output/plot_write_dicom.py
pydicom/uid.py

in doc : use class UID instead of direct str to assign a UID
in uid.py : use class UID instead of str for PYDICOM_IMPLEMENTATION_UID (and move the code block after class UID definition so that it can use this class)
Note : this seemed to me a very minor change that did not need specific testing.

[MRG] Better type hinting for UID in doc and uid.py

---

pydicom/filereader.py
pydicom/sr/coding.py

I had a non-conformant dataset with multi-valued Media Storage SOP Class UID value but was otherwise perfectly parseable.

[MRG] Improve post-read robustness for non-conformant datasets

---

doc/release_notes/v2.3.0.rst
pydicom/data/data_manager.py
pydicom/sr/coding.py
pydicom/tests/test_data_manager.py

Allow specifying the `download=False` flag for `get_testdata_file` to make sure the function doesn't send any network requests.

[MRG] Add download flag for get_testdata_file

---

doc/release_notes/v2.3.0.rst
pydicom/config.py
pydicom/filereader.py
pydicom/sr/coding.py
pydicom/tests/conftest.py
pydicom/tests/test_filereader.py

2.2.2 introduced a breaking change for where an IOError is raised for some files that contain spurious bytes with no sequence terminator (because they're not actually sequences). Since the error is raised in the data_element_generator, there is no way to circumvent this issue via fixers. Further the 2.2.2 logic change does not respect the `replace_un_with_known_vr` configuration parameter because it is now always set to SQ.  
This merge request introduces the `infer_sq_for_un_vr` which, when set to False, allows parsing of non-compliant DICOMs with data that would otherwise fail to parse as of 2.2.2.

[MRG] add infer_sq_for_un_vr config option

---

pydicom/tests/test_dataset.py
pydicom/tests/test_filewriter.py
pydicom/tests/test_handler_util.py
pydicom/tests/test_helpers.py

- avoids deprecation warnings from pytest
- fixes #1621
I did not add release notes, I think they are not needed for this.

[MRG] Do not use pytest.warns(None)

---

.circleci/config.yml
build_tools/circle/build_doc.sh

- Use a next-gen Docker convenience CircleCI image. Context: https://discuss.circleci.com/t/legacy-convenience-image-deprecation/41034

[MRG] Use a next-gen Docker convenience CircleCI image

---

doc/release_notes/v2.4.0.rst
pydicom/data/download.py

- default chunk size with progress bar was 1 byte
- fixes #1611
This is a trivial change, and I did not write a test case (which would have to be a performance test) for this. We don't have (and probably don't need) tests for download.

[MRG] Use sensible chunk size for test data download

---

doc/release_notes/v2.4.0.rst
pydicom/tests/test_valuerep.py
pydicom/valuerep.py

- use str() instead of repr() for validation -
this uses the original string if available
- fixes #1632

[MRG+1] Fix length validation of DS values

---

doc/release_notes/v2.4.0.rst
pydicom/datadict.py
pydicom/dataelem.py
pydicom/tag.py
pydicom/tests/test_dataset.py
pydicom/tests/test_tag.py

- issue a warning but don't change the private creator logic
- fixes #1638
I decided to make a minimum impact change that only prevents the crash. Any invalid private creator will still be handled as a private creator with respect to the private tags.
The crash itself only happens due to the lookup of the key in the private dictionary, which now behaves the same as a valid private creator not present in the dictionary.

[MRG] Prevent crash due to invalid private creator

---

doc/release_notes/v2.4.0.rst
pydicom/tag.py
pydicom/tests/test_tag.py

Added a new 'json_key' method to BaseTag class that returns a string, used as key for JSON representation of DICOM data, as explained in Sec F.2.1.1.2 here: https://dicom.nema.org/dicom/2013/output/chtml/part18/sect_F.2.html.

[MRG] json_key method for BaseTag

---

pydicom/multival.py
pydicom/pixel_data_handlers/numpy_handler.py

Fix source comment typo

---

doc/release_notes/v2.4.0.rst
pydicom/values.py

If the incorrect data was large, this error message was very large. Ended up with a 300MB error log output because of this on a single real dicom.

Avoid multi-megabyte error message

---

doc/release_notes/v2.4.0.rst
pydicom/dataset.py
pydicom/tests/test_json.py

- allows to ignore this case if suppress_invalid_tags is set
- fixes #1693
The problem occurred because an exception was raised during the creation of an `IS` dataelement with a float number.
This is somewhat related to #1661, which is about the fact that this exception cannot be suppressed if just reading the tags normally, which I still find unsatisfying, and we may have to find a solution there...

[MRG] Catch error in creating a dataelement in to_json_dict

---

doc/release_notes/v2.4.0.rst
pydicom/filereader.py
pydicom/tests/test_dataset.py

- a regular dataset with a Directory Storage SOP Class is now handled as a regular dataset
- see discussion in #1702

[MRG] Handle invalid DICOMDIR dataset

---

.github/workflows/merge-pytest.yml
.github/workflows/pr-pytest.yml

- CharPyLS does not compile under Linux/MacOS
- also add 3.11 builds for PR builds
I seems to have forgotten to add 3.11 builds to the PR builds, so this was not visible there.

[MRG] Skip jpeg-ls tests for Python 3.11

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/other_issues.md
README.md

- slightly adapt the issue templates
I added a couple of sentences to the README as a starting point for the discussed changes.
We probably also need some additions in the documentation itself...

[MRG] Add more information about pydicom purpose

---

doc/reference/elem.valuerep.rst
doc/release_notes/v2.4.0.rst
pydicom/config.py
pydicom/dataset.py
pydicom/tests/test_json.py
pydicom/tests/test_valuerep.py
pydicom/valuerep.py

Closes #1661.  Introduces new ISfloat class which is used if a non-integer float is passed to IS and settings allow it.

[MRG] IS float

---

.github/workflows/merge-typing.yml
.github/workflows/pr-type-spell.yml
doc/release_notes/v2.4.0.rst
pydicom/tests/test_codes.py
pydicom/tests/test_config.py
pydicom/tests/test_data_manager.py
pydicom/tests/test_dataset.py
pydicom/tests/test_encoders.py
pydicom/tests/test_encoders_pydicom.py
pydicom/tests/test_filereader.py
pydicom/tests/test_fileset.py
pydicom/tests/test_filewriter.py
pydicom/tests/test_gdcm_pixel_data.py
pydicom/tests/test_handler_util.py
pydicom/tests/test_jpeg_ls_pixel_data.py
pydicom/tests/test_numpy_pixel_data.py
pydicom/tests/test_overlay_np.py
pydicom/tests/test_pillow_pixel_data.py
pydicom/tests/test_pylibjpeg.py
pydicom/tests/test_rle_pixel_data.py
pydicom/tests/test_uid.py
pydicom/tests/test_util.py
pydicom/tests/test_valuerep.py

pytest 7.2 is now giving a large number of warnings about deprecated `setup` and `teardown` methods (which they say are `nose` tests and they will stop support for `nose` in future).
[Their recommendation](https://docs.pytest.org/en/stable/deprecations.html#support-for-tests-written-for-nose) is to simply search/replace those names to `setup_method` and `teardown_method`, which is what this PR does.

[MRG] Pytest deprecations

---

doc/release_notes/v2.4.0.rst
pydicom/pixel_data_handlers/util.py

During work with some customer dicom i have found one which had strange length for attribute:
(0028,3006) OW 0000\0000\0000\0000\0000\0000\0000\0000\0000\0000\0000\0000\0000... # 131072, 1 LUTData
which was rising error:
struct.error: unpack requires a buffer of 131070 bytes
This change just calcucate size for unpack

cut LUTData to expected size

---

.github/workflows/merge-typing.yml
.github/workflows/pr-type-spell.yml
pydicom/filewriter.py
pydicom/tests/test_config.py
pydicom/tests/test_dataelem.py
pydicom/tests/test_values.py
pydicom/valuerep.py
pydicom/values.py

Fix handling of multibyte characters with backslashes decoded in `values.convert_text`.
- Multibyte characters that contain backslash (0x5C) in their codes (e.g. 倍 in Japanese) were mishandled as separators.
- Unit test is added to test decoding of text with such characters and actual separator.

[MRG] Fix decoding of multibyte text with backslash

---

doc/tutorials/filesets.rst

Minor styling suggestions to the DICOM File-sets and DICOMDIR tutorial.

[MRG] [DOC] File-set tutorial styling suggestions

---

doc/release_notes/v2.4.0.rst
pydicom/tests/test_util.py
pydicom/util/codify.py

This PR is intended to address the issue highlighted in #1738. 
This is accomplished by checking the VR of the data element, and if it is AT (Attribute Tag), then it is a tag and should be formatted as such. Existing behavior was not modified for any other VRs.

[MRG] Ensure AT DataElements are encoded properly by code_dataelem

---

.github/workflows/merge-pytest.yml
.github/workflows/merge-typing.yml
.github/workflows/pr-pytest.yml

GitHub Actions: Upgrade to Python v3.11 production release

---

examples/dicomtree.py

In the example pydicomtree.py the function show_file() did use a global variable (sys.argv access) instead of the parameter of the function. This is okay in this example but prevents reuse of the function and was probably not intended.
Most of the tasks are not applicable since it's a minor change in a non-core component.

[MRG] small bugfix in example pydicomtree.py

---

.github/workflows/merge-pytest.yml
doc/old/image_data_handlers.rst
doc/release_notes/v2.4.0.rst

- does not compile, see #1788
For the time being, just exclude JPEG-LS builds for Python > 3.10 and add a note in the transfer syntax table.

[MRG] Exclude CharPyLS for Python 3.11

---

.github/workflows/merge-pytest.yml
.github/workflows/pr-pytest.yml
doc/tutorials/installation.rst

- avoids having to build it using cython
The last `pyjpegls` related PR for now, I promise!

[MRG] Use wheel packages to install pyjpegls

---

src/pydicom/dataset.py
src/pydicom/sequence.py
tests/test_dataset.py
tests/test_sequence.py

Fix for #1813.
In the `__deepcopy__` methods of `Sequence` and `Dataset`, the returned object should be initialised to an instance of the type of `self` rather than the literal `Dataset` and `Sequence` types. This way the methods also work for subclasses.
Since this has caused some significant issues with highdicom, wsiDicomizer, and possibly other libraries, would you consider a 2.4.1 patch release for this fix?
- [ x] Unit tests added that reproduce the issue or prove feature is working
- [ x] Fix or feature added
- [ x] Code typed and mypy shows no errors
- [ x] Unit tests passing and overall coverage the same or better

Fix deepcopy of Dataset and Sequence

---

.github/workflows/merge-pytest.yml
.github/workflows/merge-typing.yml
.github/workflows/pr-pytest.yml
.github/workflows/pr-type-spell.yml
CONTRIBUTING.md
README.md
asv.conf.json
build_tools/circle/build_doc.sh
build_tools/circle/push_doc.sh
doc/conf.py
pyproject.toml
util/generate_dict/generate_private_dict.py

Found instances of old main branch name still in use
* checked gdcm private dict file, still 'master', but cleaned up the setting of the url.
* pinned mypy, as already got a new 'error' that wasn't there in last commit

Update names to new "main" branch

---

doc/release_notes/v3.0.0.rst
src/pydicom/fileset.py
tests/test_fileset.py

Related issue: #1818 .
- Added information for incorrect tags in exception message.
- Added reference to DICOM PS3.3 Section 5.1 in the message
- Updated unit tests
TODOs:

[WIP] Additional info in exception message for fileset::add

---

doc/release_notes/v3.0.0.rst
src/pydicom/values.py
tests/test_filereader.py
tests/test_values.py

- convert_AE_String handles incorrect value length gracefully
- convert_tag now raises if the byte_string is too short
These are minor changes related to the previously skipped tests. `convert_AE_String` had previously warned for incorrect length, but than crashed - it now just ignores extra bytes.
`convert_tag` is only used in `convert_AE_String`, but on the chance it is used from outside I raise an exception if the byte string is too short (instead of letting it just crash).

[MRG] Add error handling to convert_tag and convert_AE_string

---

doc/release_notes/v3.0.0.rst
src/pydicom/dataset.py
src/pydicom/encoders/base.py
src/pydicom/pixel_data_handlers/gdcm_handler.py
src/pydicom/pixel_data_handlers/jpeg_ls_handler.py
src/pydicom/pixel_data_handlers/pillow_handler.py
src/pydicom/pixel_data_handlers/pylibjpeg_handler.py
src/pydicom/pixel_data_handlers/rle_handler.py
src/pydicom/pixel_data_handlers/util.py
tests/test_dataset.py
tests/test_handler_util.py

- NumberOfFrames = 0 is now handled as 1, with a user warning issued on reading the pixel data
- closes #1844
There was already a helper function to get the number of frames and warn on incorrect values - I just adapted it to work for the value 0, and used it. This changes the behavior with respect to warnings: a warning is now issued on reading the data for a dataset with an invalid `NumberOfFrames`. I think we also may configure if the warning is shown depending on the current warning configuration, but as this is something that will be reworked anyway, I left it out for now.

[MRG] Add handling of a NumberOfFrames = 0

---

doc/release_notes/v3.0.0.rst
doc/tutorials/installation.rst
src/pydicom/pixel_data_handlers/gdcm_handler.py
src/pydicom/pixel_data_handlers/pylibjpeg_handler.py
tests/test_gdcm_pixel_data.py
tests/test_pylibjpeg.py

* Change code to copy the pixel module to avoid making changes to the dataset as originally intended (closes #1689)
* Updates the install tutorial to refer to the `main` branch

[MRG] Stop GDCM and pylibjpeg handlers modifying Pixel Representation

---

doc/reference/uid.rst
doc/release_notes/v3.0.0.rst
src/pydicom/encoders/base.py
src/pydicom/pixel_data_handlers/gdcm_handler.py
src/pydicom/pixel_data_handlers/pylibjpeg_handler.py
src/pydicom/uid.py
tests/test_handler_util.py
tests/test_pylibjpeg.py
tests/test_uid.py

* Removes UIDs and various List[UID] [deprecated in v2.1](https://pydicom.github.io/pydicom/stable/release_notes/index.html#id9)
* Changes the UID value for `JPEGLossless` to `1.2.840.10008.1.2.4.57` in line with [planned change](https://pydicom.github.io/pydicom/stable/release_notes/index.html#id9)
* Adds [various new MPEG and SMPTE UIDs](https://dicom.nema.org/medical/dicom/current/output/chtml/part06/chapter_A.html)

[MRG] Remove deprecated UIDs, add new UIDs

---

doc/release_notes/v3.0.0.rst
src/pydicom/fileset.py
tests/test_fileset.py

* Reduces the available characters for `fileset.generate_fileset()` from [0-9,A-Z] to [0-9,A-I,K-Z]
* Changes the theoretical maximum number of instances supported by `FileSet` to 35^6 (down from 36^6) to better support 32-bit systems (closes #1743)
Technically I don't need to change `generate_fileset()` but thought it would be good for it to be consistent with the FileSet file ID naming scheme.

[MRG] Reduce theoretical maximum size of file-sets to support 32-bit systems

---

doc/guides/encoding/encoder_plugins.rst
doc/old/base_element.rst
doc/old/getting_started.rst
doc/tutorials/contributing_code.rst
doc/tutorials/contributing_docs.rst
doc/tutorials/dataset_basics.rst

- also a few links used the old structure
Noticed these accidentlly after I made the other documentation PR.

[MRG] Replace master by main in documentation links

---

doc/release_notes/v3.0.0.rst
pyproject.toml
src/pydicom/dataset.py
src/pydicom/encoders/base.py
src/pydicom/sequence.py
src/pydicom/util/codify.py
tests/test_config.py
tests/test_dataset.py

Missed a couple of deprecations...
* Remove deprecated `Dataset.parent` and `Sequence.parent` properties
* Convert `Dataset` to `FileMetaDataset` when setting `Dataset.file_meta`, this seemed better to me than just forcing the `FileMetaDataset` requirement

[WIP] Remove Dataset.parent and change Dataset.file_meta

---

doc/release_notes/v3.0.0.rst
src/pydicom/valuerep.py
tests/test_valuerep.py

Python 3.11 changed the behaviour of f-strings when used with Enums + a str mixin.
Closes #1874

[MRG] Fix VR enum returning invalid value with f-strings

---

doc/release_notes/v3.0.0.rst
src/pydicom/pixel_data_handlers/pillow_handler.py

[Pillow 10.1 changed](https://github.com/python-pillow/Pillow/pull/7307) the `Image.mode` property to be read-only, with [Image._mode intended to be read-write](https://github.com/python-pillow/Pillow/pull/7271#issuecomment-1666593551).
Closes #1907

[MRG] Fix Pillow raising AttributeError due to Image.mode being read-only

---

src/pydicom/pixel_data_handlers/pillow_handler.py

The latest version of Pillow has prevented `_mode` from being set - https://pillow.readthedocs.io/en/stable/releasenotes/10.1.0.html#setting-image-mode
I noticed that https://github.com/pydicom/pydicom/pull/1908 responded to this by setting the internal `_mode` attribute instead.
I wondered if there was a better way to perform the task, rather than interacting further with Pillow's internals, and I found that [`draft()`](https://pillow.readthedocs.io/en/stable/reference/Image.html#PIL.Image.Image.draft) did the trick, simplifying the code considerably and switching to only using Pillow's public API.
`tests/test_pillow_pixel_data.py::TestPillowHandler_JPEG::test_array` continues to pass with this new version.
It's not immediately apparent to me how to check coverage, but given that I'm not …

[MRG] Use Pillow draft method instead of setting tile and mode directly

---

doc/old/private_data_elements.rst
doc/release_notes/v3.0.0.rst
src/pydicom/datadict.py
src/pydicom/dataset.py
tests/test_dataset.py

- complements the existing get_private_item
- for known tags, providing the VR is optional

[MRG] Added convenience method Dataset.add_private to add a private tag

---

doc/release_notes/v3.0.0.rst
doc/tutorials/filesets.rst
src/pydicom/fileset.py
tests/test_fileset.py

Closes #1922, use a random UUID as the filename when adding a `FileInstance` to a `FileSet`

[MRG] Change FileInstance to use a random UUID when adding to a FileSet

---

doc/release_notes/v3.0.0.rst
src/pydicom/dataelem.py
src/pydicom/dataset.py
tests/test_dataset.py

Closes #1816, fixes `deepcopy` after `Dataset.update()`
Issue caused by the deepcopy of sequence elements trying to run on `DataElement.parent` (which then goes back down to try to `deepcopy` the incompletely copied sequence `DataElement`).
I also fixed `Dataset.update()` not updating the parent dataset for the updated SQ elements.

[MRG] Fix deepcopy after Dataset.update()

---

doc/release_notes/v3.0.0.rst
src/pydicom/cli/main.py
src/pydicom/data/data_manager.py
tests/test_data_manager.py

- same for get_testdata_file called with absolute file pattern
As discussed in #1918

[MRG] Raise ValueError if get_testdata_file is called with absolute path

---

tests/test_data_manager.py

* Closes #1697, check to see if can write to the pydicom-data data directory before running the tests that require write-access.
I tested these locally by making `DATA_SRC` read-only and checking that the tests were skipped.

[MRG] Fix PermissionErrors when running data manager tests on a read-only filesystem

---

doc/release_notes/v3.0.0.rst
src/pydicom/uid.py
tests/test_uid.py

* Use a uniformly distributed random integer from [randbelow](https://docs.python.org/3/library/secrets.html#secrets.randbelow) as a suffix when `entropy_srcs` is not used
* Reduce the maximum character limit of `prefix` to 54 (down from 63)
* Closes #1773
```python
>>> from pydicom.uid import generate_uid
>>> import collections
>>> collections.Counter(generate_uid()[26] for _ in range(100000))
Counter({'7': 11330, '6': 11153, '8': 11130, '3': 11130, '5': 11124, '9': 11091, '1': 11072, '2': 11009, '4': 10961})
```
I didn't use `uuid4()` for this case because it only supplies [~122-bits of entropy](https://en.wikipedia.org/wiki/Universally_unique_identifier#Version_4_(random)), which is roughly enough for 39 characters. Since we potentially need up to 64 characters I used `randbelow()` to …

[MRG] Improvements for generate_uid()

---

examples/dicomtree.py
examples/input_output/plot_read_rtplan.py
examples/memory_dataset.py
examples/metadata_processing/plot_add_dict_entries.py
src/pydicom/filewriter.py

* Closes #1522 by updating type hint for `dcmwrite()`
* Add some type hints for some of the examples
* Rewrite the tree view example to not use the deprecated [tkinter.tix](https://docs.python.org/3/library/tkinter.tix.html) module.

[MRG] Update examples and replace deprecated Tkinter.tix

---

doc/release_notes/v3.0.0.rst
src/pydicom/dataelem.py
tests/test_dataelem.py

* `DataElement.VM` changed to always return 1 for SQ
* Closes #1481

[MRG] Change DataElement.VM to return 1 for SQ

---

doc/release_notes/v3.0.0.rst
src/pydicom/dataelem.py
src/pydicom/dataset.py
src/pydicom/filereader.py
src/pydicom/filewriter.py
src/pydicom/sequence.py
src/pydicom/tag.py
tests/test_dataset.py
tests/test_filewriter.py
tests/test_sequence.py

* Removes the `Dataset.parent_seq`, `Sequence.parent_dataset` and `DataElement.parent` attributes.
* Removes the pickle `__getstate__` and `__setstate__` overrides in `Dataset` and `Sequence`
* Removes the `__deepcopy__` overrides in `Dataset`, `Sequence` and `DataElement`
* Adds `Dataset._pixel_rep` attribute and `Dataset._set_pixel_representation` method to replace the removed functionality for ambiguous VR correction
* Adds an `ancestors` parameter to the ambiguous VR functions to replace the removed functionality
Closes #1843

[MRG] Remove relational attributes from Dataset, Sequence and DataElement

---

doc/release_notes/v3.0.0.rst
src/pydicom/cli/show.py
src/pydicom/data/data_manager.py
src/pydicom/dataelem.py
src/pydicom/dataset.py
src/pydicom/encoders/base.py
src/pydicom/filereader.py
src/pydicom/multival.py
src/pydicom/sr/codedict.py
src/pydicom/valuerep.py
src/pydicom/values.py
tests/test_multival.py
tests/test_values.py

* Refactor `MultiValue` to remove `validation_mode` and `DSfloat`, `DSdecimal`, `ISfloat` special behaviour
* Rename `MultiString` to `multi_string`, refactor to remove `validation_mode`, simplify it and move to `values` where it's actually used
*  Used [here](https://github.com/pydicom/pydicom/blob/b54036985c6ef38b92da201234ff7c1d0abbe678/src/pydicom/values.py#L245), [here](https://github.com/pydicom/pydicom/blob/b54036985c6ef38b92da201234ff7c1d0abbe678/src/pydicom/values.py#L345), [here](https://github.com/pydicom/pydicom/blob/b54036985c6ef38b92da201234ff7c1d0abbe678/src/pydicom/values.py#L496), [here](https://github.com/pydicom/pydicom/blob/b54036985c6ef38b92da201234ff7c1d0abbe678/src/pydicom/values.py#L665) (none pass `validation_mode` arg)
* Change `ISfloat("")` to return `""` in …

[MRG] Refactor MultiValue and MultiString

---

doc/release_notes/v3.0.0.rst
src/pydicom/uid.py
tests/test_uid.py

* Adds the ability to set the corresponding dataset encoding for private transfer syntaxes
* `UID.is_transfer_syntax` now always returns `bool` (previously raised an exception if private UID)

[MRG] Add ability to set encoding for private transfer syntaxes

---

doc/release_notes/v3.0.0.rst
src/pydicom/encaps.py
tests/test_encaps.py

Fixes `encapsulate_extended()` returning incorrect values for odd-length frames, closes #1968

[MRG] Fix encapsulate_extended() for odd length frames

---

doc/release_notes/v3.0.0.rst
src/pydicom/pixel_data_handlers/jpeg_ls_handler.py
src/pydicom/pixel_data_handlers/pillow_handler.py
src/pydicom/pixel_data_handlers/pylibjpeg_handler.py
src/pydicom/pixel_data_handlers/rle_handler.py
tests/test_JPEG_LS_transfer_syntax.py
tests/test_jpeg_ls_pixel_data.py
tests/test_pillow_pixel_data.py
tests/test_rle_pixel_data.py

* Switches pixel data handlers to use `generate_pixel_data_frames`
* Closes #1774, however the underlying issue with `decode_data_sequence` remains

[MRG] Fix handlers not working with multiple fragments per frame

---

doc/release_notes/v3.0.0.rst
pyproject.toml
src/pydicom/dataset.py
src/pydicom/encaps.py
src/pydicom/filebase.py
src/pydicom/filereader.py
src/pydicom/fileutil.py
src/pydicom/filewriter.py
tests/test_dataset.py
tests/test_encoders.py
tests/test_filebase.py
tests/test_filereader.py
tests/test_fileset.py
tests/test_filewriter.py

* Complete refactor of `DicomIO`, `DicomFileLike` and `DicomBytesIO`
* `DicomIO` completely overhauled to be a better behaved base class (and made faster)
* `DicomFileLike` kept for backwards compatibility (deprecate?), but otherwise identical to `DicomIO`
* `DicomBytesIO` inherits directly from `DicomIO`
* Updated type hints for `dcmwrite()`, `dcmread()`, `Dataset.save_as()` and `FileDataset.__init__()` to be more generic 
* Closes #1395
```python
import time
from pydicom import examples, dcmread, dcmwrite
from pydicom.filebase import DicomBytesIO
from pydicom.data import get_testdata_file
ds = examples.ct
fp = DicomBytesIO()
ds.save_as(fp)
p = get_testdata_file("MR_small.dcm")
for ii in range(5):
start = time.perf_counter()
for _ in range(5 * 10**4):
fp.seek(0)
dcmread(fp) …
```

[MRG] Refactor filebase

---

.circleci/config.yml

`deploy` step is deprecated, [needs to be changed to run](https://circleci.com/docs/migrate-from-deploy-to-run/)
tests/test_encoders.py::TestDatasetCompress::test_round_trip seems to be intermittently failing, too...
](https://output.circle-artifacts.com/output/job/a02a3b64-06bf-434d-ac34-ee04cd68a75d/artifacts/0/doc/_build/html/index.html)

[MRG] Switch Circle build deploy step to run step

---

doc/release_notes/v3.0.0.rst
src/pydicom/dataset.py
tests/test_dataset.py

* Allow returning a deferred `RawDataElement` via `Dataset.get_item()`
* Closes #1873

[MRG] Allow accessing a deferred element via Dataset.get_item()

---

doc/reference/encaps.rst
doc/reference/index.rst
doc/release_notes/v3.0.0.rst
src/pydicom/encaps.py
src/pydicom/pixel_data_handlers/gdcm_handler.py
src/pydicom/pixel_data_handlers/jpeg_ls_handler.py
src/pydicom/pixel_data_handlers/pillow_handler.py
src/pydicom/pixel_data_handlers/pylibjpeg_handler.py
src/pydicom/pixel_data_handlers/rle_handler.py
tests/test_encaps.py
tests/test_encoders_pydicom.py
tests/test_gdcm_pixel_data.py
tests/test_jpeg_ls_pixel_data.py
tests/test_pillow_pixel_data.py
tests/test_pylibjpeg.py
tests/test_rle_pixel_data.py

* Adds the following encapsulation functions:
* `parse_basic_offsets`
* `parse_fragments`
* `generate_fragments`
* `generate_fragmented_frames`
* `generate_frames`
* `get_frame`
* Deprecates the following:
* `get_frame_offsets` 
* `get_nr_frames` 
* `generate_pixel_data_fragment`
* `generate_pixel_data_frame`
* `generate_pixel_data`
* `decode_data_sequence`
* `defragement_data`
* `read_item`
* Adds support for `bytes` | `BinaryIO` | `filebase.ReadableBuffer` as the encapsulated data source
* Adds support for the Extended Offsets Table
* Adds support for non-conformant big endian encoded encapsulation, probably never get used but it's there
* Adds `get_frame` to allow accessing a specific encoded frame without having to read all the preceding pixel data into memory (via BinaryIO/mmap).

[MRG] Enhancements for encaps module

---

doc/reference/uid.rst
doc/release_notes/v3.0.0.rst
src/pydicom/filereader.py
src/pydicom/uid.py
tests/test_filereader.py
tests/test_uid.py

* Adds `uid.PrivateTransferSyntaxes`
* Adds `uid.register_transfer_syntax()`
* Fixes loss of encoding for `UID(private_uid)`
* Adds support for using registered private transfer syntaxes during reading

[MRG] Add support for using registered private transfer syntaxes with dcmread()

---

.pre-commit-config.yaml
pyproject.toml

Apply some [Repo-Review](https://learn.scientific-python.org/development/guides/repo-review/?repo=pydicom%2Fpydicom&branch=main) suggestions.
I went for the low-hanging fruits, other changes are more invasive and deserve a PR of their own, such as enabling more ruff rules (#1771).
* [PC100](https://learn.scientific-python.org/development/guides/style#PC100): Has pre-commit-hooks
Must have `https://github.com/pre-commit/pre-commit-hooks` repo in `.pre-commit-config.yaml`
* [PC110](https://learn.scientific-python.org/development/guides/style#PC110): Uses black or ruff-format
Use `https://github.com/psf/black-pre-commit-mirror` instead of `https://github.com/psf/black` in `.pre-commit-config.yaml`
* [PC140](https://learn.scientific-python.org/development/guides/style#PC140): Uses mypy
Must …

[MRG] Apply Repo-Review suggestions

---

doc/release_notes/v3.0.0.rst
src/pydicom/sr/coding.py
tests/test_codes.py

When doing `SRT` to `SCT` mapping check that the code is in the snomed dict. Closes #1994.

[MRG] Handle code comparision when SRT code not in mapping

---

doc/release_notes/v3.0.0.rst
src/pydicom/dataset.py
tests/test_dataset.py
tests/test_encoders.py

When PixelData (or other pixel elements) are set to `None` prior to having their value updated then `get_pixel_ids()` may sometimes return the same `id()` value because the freed memory gets reused. This PR attempts to mitigate this by resetting the `Dataset._pixel_array` and `Dataset._pixel_id` attr values to their defaults whenever the value of Pixel Data, Float Pixel Data or  Double Float Pixel Data are changed or deleted.
I couldn't come up with a way of tracking whether the pixel data values changed without creating a separate reference, which obviously isn't a great idea for a bulk data element.
Closes #1983 (again)

[MRG] Add mitigation for pixel data memory re-use issue with id()

---

src/pydicom/pixels/utils.py
tests/pixels/test_decoder_base.py
tests/pixels/test_decoder_gdcm.py
tests/pixels/test_utils.py

Makes `_passes_version_check()` more robust

[MRG] Improve robustness of version check for decoding plugins

---

src/pydicom/pixels/decoders/pylibjpeg.py
tests/pixels/pixels_reference.py
tests/pixels/test_decoder_pylibjpeg.py

`pylibjpeg-libjpeg` has been updated to use `libjpeg` v1.67 which fixes the encoding failure when a v101 Adobe APP14 marker is present.
* Bumps the required `pylibjpeg-libjpeg` to v2.1
* Updates the `pylibjpeg` tests to no longer skip JPEG files with the v101 APP14 marker

[MRG] Update to use newest pylibjpeg-libjpeg release

---

src/pydicom/pixels/decoders/base.py
tests/pixels/pixels_reference.py
tests/pixels/test_decoder_gdcm.py
tests/pixels/test_decoder_pillow.py
tests/pixels/test_decoder_pylibjpeg.py

Checks the JPEG/JPEG-LS codestream for a JFIF marker (which implies YBR) or component IDs corresponding to to the ASCII values for RGB (which implies RGB), closes #2029

[MRG] Check for JFIF and component IDs when determining decoded colour space

---

src/pydicom/config.py
src/pydicom/encaps.py
src/pydicom/filereader.py
src/pydicom/fileset.py
src/pydicom/fileutil.py
src/pydicom/jsonrep.py
src/pydicom/pixels/decoders/rle.py
src/pydicom/util/leanread.py
src/pydicom/valuerep.py
tests/pixels/test_decoder_rle.py
tests/pixels/test_encoder_base.py
tests/pixels/test_processing.py
tests/test_JPEG_LS_transfer_syntax.py
tests/test_charset.py
tests/test_codes.py
tests/test_data_manager.py
tests/test_dataelem.py
tests/test_dataset.py
tests/test_dictionary.py
tests/test_encaps.py
tests/test_errors.py
tests/test_filereader.py
tests/test_fileset.py
tests/test_filewriter.py
tests/test_handler_util.py
tests/test_json.py
tests/test_rle_pixel_data.py
tests/test_util.py
tests/test_valuerep.py
tests/test_values.py

https://docs.astral.sh/ruff/rules/single-line-implicit-string-concatenation/

[MRG] Apply ruff/flake8-implicit-str-concat rule ISC001

---

.github/workflows/PR.yml
tests/pixels/pixels_reference.py
tests/test_pillow_pixel_data.py

* Changed to `allclose()` with `atol=1` for J2K lossy tests because `array_equal()` has started failing with GDCM and Pillow on MacOS for some reason.
* Added the MacOS runner to the PR workflow given the difference in results to Ubuntu/Windows
Closes #2048

[MRG] Fix tests for J2K lossless decoding with MacOS

---

.github/workflows/PR.yml
.github/workflows/merge.yml
.github/workflows/tests_wf.yml

Codecov upload still isn't working in the merge workflow. I think the token needs to be [shared across workflows](https://docs.github.com/en/actions/using-workflows/reusing-workflows#using-inputs-and-secrets-in-a-reusable-workflow) because of the workflow_call

[MRG] Second attempt at codecov fix

---

.github/workflows/PR.yml
.github/workflows/merge.yml

[MRG] Third attempt to fix codecov uploads

---

.github/workflows/PR.yml
tests/test_dataset.py

Fixes test failure due to `dict.__ror__()` being added to PyPy 3.10.14 (weirdly, did they forget to remove it?)
[Passing workflow](https://github.com/pydicom/pydicom/actions/runs/9120144978/job/25076941007?pr=2057)

[MRG] Fix test for changes to dict in PyPy 3.10.14 

---

.github/workflows/PR.yml
.github/workflows/tests_wf.yml
tests/pixels/test_encoder_pylibjpeg.py
tests/test_fileset.py

The [windows tests have been failing](https://github.com/pydicom/pydicom/actions/runs/9066662441/job/24910056474) in the merge workflow but not triggering a failure.
I think the use of the multiline `run` command means if one fails then the result will still be OK if the final command succeeds. Fixed by switching to `bash` shell for all runners and fixing the failing tests in `pixels/test_encoder_pylibjpeg.py`:
* `TestJ2KEncoding.test_arr_u4_spp1`
* `TestJ2KEncoding.test_arr_u4_spp3`
* `TestJ2KEncoding.test_arr_i4_spp1`
* `TestJ2KEncoding.test_buffer_u4_spp1`
* `TestJ2KEncoding.test_buffer_i4_spp1`
I hadn't noticed how awful the lossy compression results are for 21+ bits...
[Passing run](https://github.com/pydicom/pydicom/actions/runs/9121022758/job/25079504933?pr=2058)
Also fixes …

[MRG] Fix windows test failures not triggering workflow failure

---

doc/release_notes/v3.0.0.rst
src/pydicom/pixels/decoders/pillow.py
tests/pixels/test_decoder_pillow.py

Pillow is unable to correctly decode multi-byte RGB J2K codestreams due to it's image mode limitations, so raise an exception instead of incorrectly decoding and giving a different more generic exception.
Closes #2006, closes #2059 (probably)

[MRG] Add exception for pillow decoder with multi-byte multi-sample J2K

---

doc/guides/decoding/decoder_options.rst
doc/release_notes/v3.0.0.rst
src/pydicom/pixels/decoders/base.py
tests/pixels/test_decoder_base.py
tests/pixels/test_processing.py

When *Bits Stored* < *Bits Allocated* [the unused bits are supposed to be ignored](https://dicom.nema.org/medical/dicom/current/output/chtml/part05/chapter_8.html#sect_8.1):
> For example, in Pixel Data with 16 bits (2 bytes) allocated, 12 bits stored, and bit 11 specified as the high bit, one pixel sample is encoded in each 16-bit word, with the 4 most significant bits of each word not containing Pixel Data. See [Annex D](https://dicom.nema.org/medical/dicom/current/output/chtml/part05/chapter_D.html) for other examples of the basic encoding schemes.
> ...
> Receiving applications may not assume anything about the contents of unused bits, and in particular may not assume that they are zero, or that they contain sign extension bits.
However in > 99% of cases this is irrelevant because …

[MRG] Shift bits when Bits Stored is less than Bits Allocated

---

src/pydicom/pixels/processing.py
tests/pixels/test_processing.py

The RGB <-> YCbCr colour space conversion is only valid for 8-bit unsigned data, so raise an exception if that's not the case. Added to prevent the default YCbCr to RGB transform when decoding/decompressing if it's not appropriate.

[MRG] Restrict colour space conversion to uint8 arrays

---

doc/release_notes/v3.0.0.rst
src/pydicom/dataelem.py
tests/test_json.py

Adds handling of unknown VR with InlineBinary content. This fixes two issues:
- Sequences encoded in the unknown VR were not correctly read. (See #2062)
- Values encoded in the content were not correctly un-padded.
fixes #2062
Maybe it would be better to extend the constructor of `DataElement` to accept `value` as a bytes - the documentation for the class doesn't allow for this, but there seems to be some preliminary handling of UN in there.

[MRG] Improve handling of Json inline binary UN. Fixes #2062

---

doc/release_notes/v3.0.0.rst
src/pydicom/pixels/decoders/pillow.py
src/pydicom/pixels/utils.py
tests/pixels/test_decoder_pillow.py
tests/pixels/test_utils.py

* Accounts for a non-conformant JP2 header when decoding JPEG 2000
Closes #2073

[MRG] Account for JP2 header if present

---

doc/guides/index.rst
doc/guides/plugin_table.rst
doc/guides/user/base_element.rst
doc/guides/user/working_with_pixel_data.rst
doc/index.rst
doc/reference/examples.rst
doc/reference/pixels.rst
doc/tutorials/dataset_basics.rst
doc/tutorials/filesets.rst
doc/tutorials/index.rst
doc/tutorials/pixel_data/compressing.rst
doc/tutorials/pixel_data/creation.rst
doc/tutorials/pixel_data/index.rst
doc/tutorials/pixel_data/introduction.rst
src/pydicom/__init__.py
src/pydicom/encaps.py
src/pydicom/examples/__init__.py
src/pydicom/pixels/__init__.py
src/pydicom/pixels/common.py
src/pydicom/pixels/decoders/base.py
src/pydicom/pixels/processing.py
src/pydicom/pixels/utils.py
tests/pixels/test_common.py
tests/pixels/test_decoder_base.py
tests/pixels/test_decoder_pylibjpeg.py
tests/pixels/test_encoder_base.py
tests/pixels/test_utils.py
tests/test_examples.py

* Adds pixel data tutorial
* Adds `examples.get_path()` and updates documentation to use it instead of `get_testdata_path()`
* Various small user improvements, mostly better exception messages
* Fixes planar configuration not being set properly with `Decoder.iter_pixels()`
* Adds a check of dataset compression state to `decompress()`
Closes #2031

[MRG] Add pixel data tutorial, various small improvements

---

src/pydicom/dataset.py
src/pydicom/filereader.py
src/pydicom/filewriter.py
tests/test_dataset.py

Hi,
I have a very common use case in my app where we read a dicom, edit some tags, and write it back.  
I noticed that for some of the users, CPU usage was significantly higher than other cases.  
I ran a profiler and noticed that `correct_ambigous_vr` usage was significantly higher than usual.  
When debugging, I noticed that `is_original_encoding` returns `False` for every dicom that has `SpecificCharacterSet` (originally) set to a value that is different than the default.  
This happens because Dataset._parent_encoding isn't being set at `dcmread`.
This PR introduces a few changes to mitigate it:
* `read_dataset` sets `parent_encoding` for the dataset it creates. This reduces calls to `correct_ambigous_vr` in the first place.
* `_read_file_meta` sets original encoding to remove …

[MRG] Improve performance for non-default encoding

---

doc/release_notes/v3.0.0.rst
src/pydicom/dataelem.py
src/pydicom/filewriter.py
tests/test_filewriter.py

* Always writes the first value for elements such as *LUT Descriptor* using **US**
* Fixes validation for setting elements such as *LUT Descriptor*
* Closes #2081

[MRG] Fix writing elements like LUT Descriptor when VR is SS

---

doc/reference/pixels.rst
doc/reference/pixels.utils.rst
doc/release_notes/v3.0.0.rst
src/pydicom/dataelem.py
src/pydicom/dataset.py
src/pydicom/pixels/__init__.py
src/pydicom/pixels/utils.py
tests/pixels/test_utils.py
tests/test_dataelem.py

* Adds `set_pixel_data()` which sets the Image Pixel module elements using an `ndarray`
* Adds `Dataset.set_pixel_data()` which wraps `set_pixel_data()`
* Adds an exception to DataElement if setting *Pixel Data* directly using an `ndarray`
Closes #50, finally :fireworks: :champagne: :pinata:

[MRG] Add Dataset method and function to set Image Pixel elements using an ndarray

---

doc/release_notes/v3.0.0.rst
src/pydicom/dataset.py
tests/test_json.py

* Errors during conversion to JSON changed to be more verbose and use `logging.WARNING`
Closes #1909

[MRG] Make JSON conversion errors more verbose at a lower level

---

doc/release_notes/v3.0.0.rst
src/pydicom/dataset.py
src/pydicom/filebase.py
src/pydicom/filereader.py
src/pydicom/util/codify.py
tests/test_dataset.py
tests/test_filebase.py
tests/test_filereader.py
tests/test_util.py

* Adds `FileDataset.buffer` which is the object used for deflated datasets and datasets read from a buffer-like such as `BytesIO`
* `FileDataset.filename` is now only either a filename `str` or `None`
* Adds a `name` setter for `DicomIO`
* Keeps the filename used for deflated datasets read using path or file-like
* `copy.copy()` operation on `FileDataset` will return a shallow copy with the `self.buffer` object shared rather than set to `None` if closed (I believe this is in keeping with the expected behaviour for `copy.copy()`?)
* `copy.deepcopy()` operation on `FileDataset` will return a deep copy and only set `self.buffer` to `None` if unable to perform a deep copy on it.
Closes #1937
I'd be happy to change the attribute name to something other than `buffer`.

[MRG] Add FileDataset.buffer attribute, general fixes for datasets read from buffer-likes

---

tests/test_misc.py

LOG009 Use of undocumented `logging.WARN` constant

[MRG] Apply ruff/flake8-logging rule LOG009

---

doc/release_notes/v3.0.0.rst
src/pydicom/dataset.py
src/pydicom/filewriter.py
tests/test_dataset.py
tests/test_fileset.py
tests/test_filewriter.py

* Raise `FileExistsError` by default with `Dataset.save_as()` and `dcmwrite()` when given the path to a filename
* Closes #2104 
* Update exception messages matches in tests to account for PyPy

[MRG] Add argument to raise FileExistsError when writing

---

README.md
src/pydicom/valuerep.py
tests/pixels/test_processing.py
tests/test_charset.py
tests/test_filewriter.py
tests/test_util.py
tests/test_valuerep.py

* Catches missed logged warnings in the tests
* Update README to remove contrib-pydicom mention
* Cleaner validation warning for DSdecimal (either too long warning, or invalid warning, not both)
* Use `original_string` value with DSdecimal if auto_format is False... it was flagging DSdecimal("1.2345") as invalid.
* Refactored the buffer test since it's taking a weirdly long time in the workflow.
The validation warnings with IS/DS are a bit messy. I think either the validation should be done externally by the validation checks in `valuerep`, or internally by the class `__init__`. Currently it's both, so you can get two warnings about the same invalid value.

[MRG] Catch missed test warnings, clean up validation warnings with DSdecimal

---

src/pydicom/pixels/processing.py

I think the differences between `apply_voi_lut()`, `apply_voi()`, and `apply_windowing()` could be a bit more emphasized in the API reference.
Here is a first suggestion. Can you think of further/other improvement ideas?
*Note:* only doc comments were changed.

Improvment idea: Docs of apply_voi(_lut)()

---

doc/release_notes/v3.0.1.rst
doc/release_notes/v3.1.0.rst
pyproject.toml
src/pydicom/config.py
src/pydicom/pixels/utils.py
tests/pixels/test_decoder_gdcm.py
tests/pixels/test_utils.py

* Setup debugging/logging earlier to avoid having it undefined during import process
* Reduces the amount of logging when `pixels` plugin imports are missing.
* Closes #2128

[MRG] Reduce logging for missing imports

---

doc/release_notes/v3.1.0.rst
src/pydicom/data/hashes.json
src/pydicom/data/urls.json
src/pydicom/pixels/common.py
src/pydicom/pixels/decoders/base.py
src/pydicom/pixels/encoders/base.py
tests/pixels/pixels_reference.py
tests/pixels/test_common.py
tests/pixels/test_decoder_base.py
tests/pixels/test_utils.py

Address #2134 by:
- Changing the `RunnerBase.frame_length()` method to return a float for the `"bytes"` option in the situation that a frame has a length that is not a multiple of 8.
- Change `DecoderBase._validate_buffer()` method to calculate the expected length accounting for non byte-aligned frames, thus allowing correct decoding of these images.
- Change the `Decoder._as_array_native()` method to account for non byte-aligned frames. Also give `Decoder._as_buffer_native()` the same treatment, however in this case it is not clear what the correct behaviour should be if the caller requests a single frame index for an image with non-byte aligned frames, since any returned `bytes` could include pixels from neighbouring frames. Therefore I just throw a `RuntimeError` in this situation. If …

[MRG] Fix single bit native decoding for images with non byte-aligned frames

---

.python-version
doc/release_notes/v3.1.0.rst
src/pydicom/dataset.py
src/pydicom/pixels/utils.py
tests/pixels/test_utils.py

Extends the `set_pixel_data` function (and hence also the corresponding method of the `Dataset` class) to accept numpy arrays with dtype of `bool`, and in this case uses bit-packing to set the array with *BitsAllocated* of 1. Implements as discussed in #2141.
I also added a tentative line to the release notes, however it seems the versioning there is out of sync with actual github/PyPI releases (features in 3.0.1 release are described in the document for upcoming 3.1.0 release).

[MRG] `set_pixel_data` with boolean array for bit-packing

---

src/pydicom/pixels/decoders/pillow.py
src/pydicom/pixels/decoders/pyjpegls.py
src/pydicom/pixels/decoders/pylibjpeg.py
src/pydicom/pixels/encoders/pyjpegls.py
src/pydicom/pixels/encoders/pylibjpeg.py
src/pydicom/pixels/utils.py
tests/pixels/test_decoder_pyjpegls.py
tests/pixels/test_decoder_pylibjpeg.py
tests/pixels/test_encoder_pyjpegls.py
tests/pixels/test_encoder_pylibjpeg.py

* Bump required versions for `pyjpegls`, `pylibjpeg-libjpeg`, `pylibjpeg-openjpeg` and `pillow`
* Update tests for big endian mostly to make the dtype endianness explicit
* Remove test exceptions for decoding 9-bit J2K with Pillow (fixed in v10.3)
* Make `_passes_version_check()` a bit more forgiving so it allows things like "2.4.0.dev0" when compared to (2, 4)
Closes #2147

[MRG] Fixes for pixel data handling using pyjpegls and pylibjpeg on big endian systems

---

src/pydicom/data/download.py
tests/test_data_manager.py

Changes a data manager test to delete the data file from a temporary copy of the `.pydicom/data` cache rather than the real thing so the original doesn't have to keep downloading the deleted file. If for whatever reason you can't download the file then your other tests that depend on that file then fail.

[MRG] Stop data manager test from altering the data cache

---

doc/release_notes/v3.1.0.rst
src/pydicom/dataelem.py
tests/test_dataset.py

Fixes being unable to pickle datasets with LUT Descriptor elements, closes #2160

[MRG] Fix being unable to pickle datasets with LUT Descriptor

---

.github/dependabot.yml
.github/workflows/PR.yml
.github/workflows/merge.yml
.github/workflows/publish-pypi-deploy.yml
.github/workflows/tests_wf.yml
doc/release_notes/v3.1.0.rst
pyproject.toml
src/pydicom/data/data_manager.py
src/pydicom/pixels/utils.py
tests/test_dataset.py

Closes #2172.
Update PR workflows to add Python 3.13 and Python 3.14 (pre-release).
It appears numpy is not available for Python 3.14 pre-release, so added workflow flag for whether numpy tests are executed (default true).

[MRG] Python 3.13, 3.14a added to CI

---

doc/guides/cli/cli_codify.rst
doc/guides/cli/cli_intro.rst
doc/guides/cli/cli_show.rst
doc/release_notes/v3.1.0.rst
src/pydicom/cli/main.py
src/pydicom/data/data_manager.py
tests/test_cli.py

Closes issue #2177.
Allow tags in CLI filespec in format (gggg,eeee), wherever a DICOM keyword could be used.
Also cleaned up (parametrized, separated by intent) some of the CLI tests.

[MRG] CLI tag numbers allowed

---

.github/workflows/PR.yml
pyproject.toml

Avoid specifying dev tools twice. When using pre-commit, specify dev tools in the pre-commit config file.
Accordingly, no need to run mypy twice, both in pre-commit and in a GitHub job. Let pre-commit handle that.

[MRG] Let pre-commit specify and run its dev tools

---

doc/conf.py

Fixes source code links in the API not pointing to the correct URLs since the change to `src/pydicom`
Also, I really like the [pydata sphinx theme](https://pydata-sphinx-theme.readthedocs.io/en/stable/) (as used by matplotlib and pandas), does anyone else want to switch?

Fix broken source links in the documentation

---

.github/workflows/tests_wf.yml
doc/guides/decoding/decoder_options.rst
doc/guides/encoding/jpeg_2k.rst
doc/guides/encoding/jpeg_ls.rst
doc/guides/encoding/rle_lossless.rst
doc/guides/glossary.rst
doc/guides/user/working_with_pixel_data.rst
doc/release_notes/v3.1.0.rst
doc/tutorials/pixel_data/compressing.rst
src/pydicom/pixels/common.py
src/pydicom/pixels/decoders/base.py
src/pydicom/pixels/processing.py
tests/pixels/test_processing.py
tests/test_gdcm_pixel_data.py

* Add support for up to 16-bit input arrays for converting to/from YBR_FULL*
* Add support for converting to/from 8-bit YBR_PARTIAL*
* Closes #2210 
* Fixes codecov upload failures
YBR_PARTIAL only supports 8-bit because it's a specialised form of YCbCr with a reduced value range that doesn't make sense to extend to higher (or lower) bit-depths.

Enhancements for colour space conversions

---

doc/release_notes/v3.1.0.rst
src/pydicom/hooks.py
src/pydicom/values.py
tests/test_dataelem.py

- this had been the case before, but had changed for numeric values some time ago
This was not a real bug, just a convenience, if anyone relies on this (I myself had, see [this issue](https://github.com/pydicom/dicom-validator/issues/165)).

Make sure MultiValue is used for values with VM>1

---

doc/release_notes/v3.1.0.rst
src/pydicom/examples/__init__.py

- if the example data are not found locally for some reason, they should not be looked up externally
- fixes #2223
Instead of changing the default for `dowload`, this just avoids the download in the import if the example data is not available for some reason (they are not available remotely anyway). This does not change the behavior in any other way.

Don't try to download on importing examples

---

doc/release_notes/v3.1.0.rst
src/pydicom/pixel_data_handlers/gdcm_handler.py
src/pydicom/pixels/decoders/gdcm.py
src/pydicom/pixels/encoders/base.py
tests/pixels/test_decoder_gdcm.py
tests/pixels/test_encoder_base.py
tests/pixels/test_utils.py
tests/test_gdcm_pixel_data.py

It appears that due to SWIG limitations `gdcm.Image.GetBuffer()` cannot return more than 2^(X - 1) - 1 bytes of data, where X is the size of the C++ `int` type on the user's PC (a guaranteed minimum of 16-bit but typically 32). 
This PR changes the following:
* Require GDCM > 2.8.8 for v2 backend (v3 backend already requires > 3.0.10)
* Raise an exception whenever an individual frame will exceed a `GetBuffer()` limit of 2^31 - 1
* Split decoding of multi-frame pixel data where each individual frame is lower than the 2^31 - 1 limit but the total decoded pixel data will be greater than it.
* Closes #2227 
* Changes encoding to prefer pylibjpeg over GDCM for RLE Lossless (because it's faster and more conformant)

Add workarounds for GDCM decoding failures for large pixel data

---

src/pydicom/fileutil.py

This small PR resolves the annoying deprecation warnings of the `logger` library:
```python
DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
```

Migrate to modern logger interface

---

doc/guides/encoding/jpeg_ls.rst

Corrected a typo in `doc/guides/encoding/jpeg_ls.rst`.
Fixed incorrect values in the RGB examples for JPEG Lossless and JPEG-LS Near-Lossless.

[MRG] Fix typo in documentation

---

doc/release_notes/v3.1.0.rst
src/pydicom/filewriter.py
tests/test_filewriter.py

- the setting had only been used for values supporting multiple encodings
- see #2243

Use writing_validation_mode for writing ASCII values

---

doc/release_notes/v3.1.0.rst
src/pydicom/jsonrep.py
tests/conftest.py
tests/test_json.py

- if represented as empty strings they could cause an exception
- fixes #2221

Correctly handle empty json values

---

doc/release_notes/v3.1.0.rst
src/pydicom/filewriter.py
tests/test_filewriter.py

- warn or raise on the error
- fixes #2238

Correctly handle empty LUT data

---

tests/test_data_manager.py

Recent changes in https://github.com/pydicom/pydicom/pull/2240 added a hard-coded number of test files to a test of the data manager. This means that any pull request that introduces new test files fails. I assume this was not deliberate, as it doesn't seem to be useful to check the exact number of files. For example merge tests on #2216 are currently failing because of this. See [here](https://github.com/pydicom/pydicom/actions/runs/16543684622/job/46788400137?pr=2216):
```
FAILED tests/test_data_manager.py::test_fetch_data_files_download_failure - AssertionError: Regex pattern did not match.
Regex: "The following exception\\(s\\) occurred trying to download the data files\\n  'RuntimeError: No network!' for 693_J2KR.dcm, 693_UNCI.dcm and 77 others"
Input: "The following exception(s) …
```

[MRG] Remove hardcoded number of test files

---

doc/release_notes/v3.1.0.rst
src/pydicom/uid.py
tests/test_uid.py

* Add support for registering unknown public transfer syntaxes via `register_transfer_syntax()`.
* Disallow registering the same UID twice

Add support for registering public transfer syntaxes

---

doc/release_notes/v3.1.0.rst
pyproject.toml
src/pydicom/pixels/decoders/base.py
tests/pixels/pixels_reference.py
tests/pixels/test_decoder_base.py
tests/pixels/test_decoder_pylibjpeg.py
tests/test_tag.py

* Fixes not performing bit shifting with J2K and JLS if no sign correction needed but a bit shift is
* Changes the bit shift amount with J2K and JLS to only use codestream precision when it's less than *Bits Stored* to prevent any data in the unused high bits being returned 
* Related to #2260
I still have to create a separate PR to address how to handle the "unused" high bits on the encoding side.

Fix sometimes including unused high bits when decoding J2K and JLS
