pydicom/pydicom

- tests/test_filereader.py
Makes sure to test that the PlanarConfiguration are actually different.
> Cleaned up test for PlanarConfiguration

- pydicom/uid.py
- tests/test_uid.py
Allows deterministic results if desired.  Also improves UID validation and tests.
> ENH: Improve uniqueness in generated UID values

- pydicom/util/codify.py
- source/generate_dict/generate_dict_2015b.py
- source/generate_dict/generate_uid_2015b.py
Added parenthesis to print calls so it is compatible with both python 2 and 3.
> Added parenthesis to print calls

- docs/getting_started.rst
> Fix the broken pip install command

- pydicom/dataelem.py
- pydicom/filereader.py
- pydicom/filewriter.py
- pydicom/valuerep.py
- pydicom/values.py
- tests/test_filewriter.py
- tests/test_multival.py
- tests/test_valuerep.py
Closes #228 and #212
* multi-valued DA, DT, TM data elements
* config.datetime_conversion was not properly set
* allow empty dates and times
> Fixes for DA, DT, TM data elements

- pydicom/compat.py
- pydicom/config.py
- pydicom/contrib/pydicom_PIL.py
- pydicom/dataelem.py
- pydicom/dataset.py
- pydicom/examples/dicomtree.py
- pydicom/examples/show_charset_name.py
- pydicom/filebase.py
- pydicom/filereader.py
- pydicom/misc.py
- pydicom/tag.py
- pydicom/uid.py
- pydicom/util/fixer.py
- pydicom/util/leanread.py
Mainly whitespaces removed or added...
> Fix Landscape Style warnings

- pydicom/dataset.py
- pydicom/filereader.py
- allows usage of pyfakefs
- fixes issue #259
> Use os.stat instead of stat

- pydicom/dataset.py
- pydicom/encaps.py
Fixes https://github.com/darcymason/pydicom/issues/269
> Fixes for Python 3 - ensure byte strings are explicitly marked as such

- pydicom/dataset.py
Fixed an issue in 76603f8aaa (PR #271) where the fix was being applied to uncompressed files.
> Fixed an issue in 76603f8aaa (PR #271) where the fix was being applied to uncompressed files.

- pydicom/examples/write_new.py
disclaimer: this is from reading the documentation, review welcome!
> add example how to format date/time for DICOM

- pydicom/dataelem.py
- pydicom/dataset.py
- tests/test_dataelem.py
- tests/test_dataset.py
> Add equality/inequality operators to Dataset and DataElement

- pydicom/filewriter.py
- pydicom/valuerep.py
- pydicom/values.py
- tests/test_filereader.py
- tests/test_filewriter.py
> Add support for DICOM elements with a VR of 'UR'

- pydicom/dataelem.py
- tests/test_dataelem.py
> Change DataElement equality to only compare tag, VR and value, add unit test

- pydicom/values.py
- tests/test_filereader.py
> Fix for reading AE elements not stripping leading and trailing spaces

- pydicom/filewriter.py
- pydicom/valuerep.py
- pydicom/values.py
- tests/test_filereader.py
- tests/test_filewriter.py
Also added extra tests for elements with a VR of 'UR'.
Related to #216 and #295
> Added support for elements with a VR of 'UC'

- pydicom/dataset.py
Very small bug fix.
I believe this bug was mentioned [here](http://stackoverflow.com/a/28090072/4898004), but I could not find a pull request in this repository's history which referenced it. Hopefully I haven't missed one.
> Fix Referenced Before Assignment Bug

- pydicom/dataset.py
- pydicom/filewriter.py
- tests/test_filereader.py
Much nicer than my other attempt.
Related to #298 
Addresses #201, #90, #42
> Add ambiguous VR correction to dataset reading

- pydicom/dataelem.py
- pydicom/dataset.py
- pydicom/sequence.py
- pydicom/tag.py
Also a couple of PEP8 fixes.
Related to #162
> Updated Docstrings for dataelem, dataset, sequence, tag modules

- pydicom/dataset.py
- tests/test_dataset.py
> Fix for Dataset properties causing AttributeError 

- pydicom/contrib/pydicom_series.py
> Fixed to return unsigned dtype

- pydicom/encaps.py
- pydicom/filebase.py
- pydicom/filereader.py
- tests/test_filewriter.py
Addresses part of: https://github.com/darcymason/pydicom/issues/310
> Add enter and exit to DicomFileLike

- pydicom/filereader.py
- tests/test_filereader.py
> Fix for failure to read file containing only Command Set Elements

- LICENSE
Move the license in the root directory. I bump the year as well.
> [MRG] MAINT move license in root directory

- .travis.yml
- tox.ini
This is a test to start debugging how to fix up the .travis.yml to remove old versions of python. It might/should also trigger circle, who knows :)
> first test of .travis.yml with 2.6 removed

- pydicom/dataset.py
Updated __contain__ comments to understand code better.
> Update the comments for compatibility with code

- appveyor.yml
This PR adds the appveyor configuration file.
> [MRG] Add Appveyor

- CONTRIBUTING.md
works on #383
here's a contribution guide example.
cc: @scaramallion
> [MRG+2] Add contributing guide

- pydicom/filereader.py
- pydicom/fileutil.py
- pydicom/misc.py
- pydicom/util/leanread.py
- tests/test_filereader.py
- tests/test_misc.py
- added test for size_in_bytes()
- fixes #234
> [MRG] Re-enabled convenience method to define defer size as string

- Makefile
- build_tools/circle/build_doc.sh
> [MRG] Force to build always example

- build_tools/circle/build_doc.sh
> [MRG+3] Fix typo from copy-pasting from scikit-learn

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
> [MRG+2] Add issue and PR templates

- pydicom/tests/test_valuerep.py
- pydicom/valuerep.py
- needed to handle overwritten `__new__`
- fixes #199
> [MRG] Added __copy__ and __deepcopy__ to PersonNameUnicode

- pydicom/sequence.py
- makes usage more convenient, see discussion in #107
- fixes #107
> [MRG + 1] Removed address from sequence repr

- pydicom/_dicom_dict.py
- source/generate_dict/generate_dicom_dict.py
- adapted generation and generated code
- fixes #130
Another minor fix (the easiest I could find...) to get the number of issues down.
> [MRG] Only show the first VM for tags with multiple VMs in DICOM dictionary

- pydicom/dataset.py
**Reference Issue**
Closes https://github.com/pydicom/pydicom/issues/303
**What does this implement/fix? Explain your changes.**
Fix Pillow Reading on Python 3.
Update `pydicom/dataset.py` to use bytes rather than string.
**Any other comments?**
Please refer the accompanying issue for details.
> [MRG+1] Fix Pillow Reading on Python 3

- .codecov.yml
Welp I didn't intend to create a branch in the main repo. Oh well
> [MRG] Ignore tests directory in code coverage

- pydicom/dataset.py
- pydicom/tests/test_dataset.py
Fixes #462 
Dataset elements are now sorted before being compared
> [MRG+1] Fix for Dataset equality

- build_tools/circle/push_doc.sh
> [MRG+1] CI make sure to push in gh-pages

- pydicom/__init__.py
- pydicom/filewriter.py
closes #476 
Make the import of couple of classes at the top level of pydicom.
> [MRG+2] MAINT move import to top level

- pydicom/tests/test_charset.py
- pydicom/tests/test_valuerep.py
- pydicom/valuerep.py
> [MRG+1] Fix encoding not being carried over to new PN3 instance

- pydicom/filereader.py
Fixes #527
Add a trailing space to correct the exception message
> Add missing trailing space

- pydicom/_dicom_dict.py
- source/generate_dict/generate_dicom_dict.py
Updates `_dicom_dict.py` by execution of `generate_dicom_dict.py` script.
Also improves usability of `generate_dicom_dict.py` script by fixing relative path to `_dicom_dict.py` file.
> Update dicom dictionary

- pydicom/dataset.py
- pydicom/filewriter.py
#525 
Keeps track of decompression state.  On writing the dataset, confirms that dataset transfer syntax is uncompressed.
No unit testing yet.  Looking for feedback on the basic concept before finalizing the code
> [WIP] Decompression state

- README.md
- doc/image_data_handlers.rst
- doc/index.rst
- doc/pydicom_user_guide.rst
- doc/whatsnew/v1.0.0.rst
- doc/working_with_pixel_data.rst
- adapted links in README
- see #523
I checked all checkins since the last release and tried to compile a list of relevant changes.
Also updated links in README to point to GitHub Pages.
> [MRG] Updated release notes for version 1.0

- doc/base_element.rst
- doc/getting_started.rst
- doc/transition_to_pydicom1.rst
- doc/viewing_images.rst
- doc/working_with_pixel_data.rst
- fixed some typos and format issues
- fixed some broken links
- added more links to image data handlers
As it says above. The only interesting broken link was the one to http://www.pythonxy.com/, which is a roofing guide...
> [MRG] Minor documentation consolidation

- pydicom/tests/test_filewriter.py
> Fixed test depending on version length

- setup.py
> MAINT Fix documentation link in setup.py

- doc/getting_started.rst
Update the install information since that we can use conda-forge and that gdcm is also available there.
> DOC update install information

- doc/pydicom_dev_guide.rst
Adds a little detail for uploading releases.
> DOC: update developer guide PyPi release steps.

- .travis.yml
- build_tools/travis/install.sh
trying to 
closes #450 
closes #449
> MAINT install dependencies

- doc/base_element.rst
- doc/getting_started.rst
- doc/index.rst
- doc/pydicom_dev_guide.rst
- doc/transition_to_pydicom1.rst
- doc/viewing_images.rst
- doc/whatsnew/v.0.9.4.rst
- doc/whatsnew/v0.9.2.rst
- doc/whatsnew/v0.9.5.rst
- doc/whatsnew/v0.9.7.rst
- doc/whatsnew/v0.9.8.rst
- doc/whatsnew/v0.9.9.rst
- examples/input_output/plot_read_dicom_directory.py
- examples/metadata_processing/README.txt
- examples/metadata_processing/plot_anonymize.py
- fixed capitalization issues (python -> Python, dicom -> DICOM)
- fixed some typos and wording
> Fixed some minor style issues in documentation

- LICENSE
> MAINT Update license date

- pydicom/_version.py
Simple update of version to 1.0.1rc1
> Update version for 1.0 release candidate

- pydicom/dataset.py
- pydicom/tests/test_dataset.py
Addressses #464
Dataset equality changed to check only DataElements, not class members, FileDataset equality checks both.
> [MRG+1] Change Dataset equality behaviour

- LICENSE
- dicom.py
- setup.py
Merges back relevant changes made in 1.0.X branch during release process.
> Backport 1.0

- README.md
- doc/transition_to_pydicom1.rst
- see #590
Please check what else needs to go here.
> Added chapter for API changes to transition guide

- doc/pydicom_user_guide.rst
- doc/writing_files.rst
- pydicom/util/codify.py
Closes #498
Updates docs by adding section to user guide for writing files, and documents use of util/codify.py script.
> Add section Writing Files to User Guide, including codify script

- pydicom/values.py
- closes #597
see discussion in #597
> [MRG] Removed warning for incorrect date string length

- pydicom/filewriter.py
- slightly improves write performance (5-15%)
Together with the other PR this reduces the write times to be a bit less than they have been under 0.9.9, at least under Windows. I leave this as a separate PR, as it is less clear than the change in the other PR.
> [MRG+1] Use a temporary buffer in Dataset.write_data_element() to avoid seek

- doc/release-notes.rst
- doc/whatsnew/v1.1.0.rst
- pydicom/dataset.py
- pydicom/dicomdir.py
- pydicom/filereader.py
- pydicom/pixel_data_handlers/jpeg_ls_handler.py
- pydicom/pixel_data_handlers/pillow_handler.py
- pydicom/tests/test_dataset.py
- pydicom/tests/test_uid.py
- pydicom/uid.py
#256
Remove `__str__` override from `UID` to make it's behaviour more string-like, test change/additions.
Remove `__eq__`, `__ne__` and `__hash__` overrides from `UID`.
I'll leave it up to you @darcymason to decide if you want to include this change.
> [MRG+1] Improve UID behaviour

- pydicom/datadict.py
- pydicom/dataelem.py
- pydicom/dataset.py
- pydicom/filebase.py
- pydicom/tests/performance/write_profiling.py
Similar to #606, but avoids calls to Tag at source.  
This is first commit of a set of speed improvements I had done but had not folded into master.  Probably doesn't add much compared with #606, but pulling this in will cause me fewer merge problems with my subsequent commits.
Avoids calls to Tag.  Updates write profiling.
> [MRG+1] Reduce calls to Tag

- pydicom/dataset.py
Improves slicing performance by avoiding looping over all tags, and special-casing common slices such as None for start or stop.
Also avoids the (FFFF,FFFF) special case (#586)
> Improvements to dataset slicing

- appveyor.yml
> [MRG] Fix for appveyor not working with python34

- pydicom/filewriter.py
- pydicom/tests/test_filewriter.py
- fixes #632
Please check if this is what we want, and if we need more tests.
> [MRG+1] Use the properties of the write destination if they are set

- pydicom/charset.py
- pydicom/data/data_manager.py
- pydicom/datadict.py
- pydicom/dataelem.py
- pydicom/misc.py
- pydicom/tests/test_charset.py
- pydicom/tests/test_dictionary.py
- pydicom/tests/test_multival.py
- pydicom/tests/test_numpy_pixel_data.py
- pydicom/tests/test_tag.py
- pydicom/tests/test_util.py
> [MRG+1] remove unused imports

- pydicom/_dicom_dict.py
This updates module `_dicom_dict` for the latest 2018b edition of the standard.
Update was performed by running script `source/dicom_dict/generate_dicom_dict.py`.
> Update dictionary for 2018b edition

- build_tools/circle/build_doc.sh
- circle.yml
- doc/api_ref.rst
- doc/conf.py
- doc/index.rst
- doc/ref_guide.rst
- pydicom/dataset.py
- pydicom/filereader.py
- see #649
The documentation created by this PR can be accessed [here](https://858-14006067-gh.circle-artifacts.com/0/home/ubuntu/pydicom/doc/_build/html/index.html).
I did some rough categorization of the modules in the API - improvements are welcome.
> [MRG] Added API documentation chapter

- .circleci/config.yml
- build_tools/circle/push_doc.sh
> [MRG+1] Trial fix for docs not pushing back to github

- pydicom/_dicom_dict.py
- pydicom/_uid_dict.py
- closes #677
There have been very few changes in the standard, so this is a no-brainer thanks to the existing scripts...
> [MRG] Generated DICOM dictionary and UID dictionary from DICOM 2018c

- .codecov.yml
- doc/whatsnew/v1.2.0.rst
- pydicom/benchmarks/bench_encaps.py
- pydicom/encaps.py
- pydicom/tests/test_encaps.py
* Adds functions for encapsulating data, unit tests and `asv` style benchmarks. 
* Minor docstring fixes.
> [MRG+1] Add functions for encapsulating data

- README.md
- created by @darcymason
- closes #655
Another tiny change - just stumbled over that DOI issue.
> [MRG] Added badge for citation DOI

- pydicom/charset.py
- pydicom/tests/test_charset.py
- issue a warning for the misspelling
- fixes #736
> [MRG+1] Patch common spelling errors in encodings with code extensions

- examples/input_output/plot_read_dicom_directory.py
> [MRG] Fix bad element keyword in example

- doc/whatsnew/v1.2.0.rst
> [MRG] Added missing entries to release notes

- pydicom/_version.py
Updates master version to 1.3.0.dev0, following release of 1.2.0 on 1.2.X branch.
> Update version to 1.3.0 dev

- doc/conf.py
- doc/sphinxext/sphinx_issues.py
- doc/whatsnew/v1.2.0.rst
There have been a few references to pull requests in the release notes, but no links have been created for them in the generated documentation. Therefore the issue link sphinx extension has been extended to also [support pull requests](https://127-65673081-gh.circle-artifacts.com/0/home/circleci/project/doc/_build/html/whatsnew/v1.2.0.html).
> [MRG] Added support for PR links in release notes

- doc/base_element.rst
- doc/whatsnew/v1.3.0.rst
- pydicom/dataset.py
- pydicom/filereader.py
- pydicom/tests/test_dataset.py
- pydicom/tests/test_valuerep.py
- fixes Python 3.6.7/3.7.1 problems
- fixes failed AppVeyor tests (test only, just to make the build green...)
Probably best to rebase-merge the 2 commits.
> Cherry-picked fixes from master

- examples/metadata_processing/plot_anonymize.py
> fix wrong date format

- .circleci/config.yml
- allows to use the latest working version
- fixes #830
> [MRG] Use a less specific Circle.CI docker image

- README.md
Avoid "There is a newer version of this record available."
> update DOI in README

- doc/whatsnew/v1.3.0.rst
- pydicom/dataset.py
- pydicom/tests/test_dataset.py
- makes it work in a NumPy array
- see #836
> [MRG] Derive Dataset from dict

- doc/whatsnew/v1.3.0.rst
- pydicom/dataset.py
- pydicom/tests/test_dataset.py
> Handle Dataset.pop() and setdefault() with tuple and keyword args

- doc/base_element.rst
- doc/private_data_elements.rst
- doc/pydicom_user_guide.rst
- doc/python2_support.rst
- doc/ref_guide.rst
- doc/warn_transition_to_pydicom1.rst
Closes #867 
Various cleanup of docs, added new page for private data elements,
> [MRG] V1.3 Documentation Updates

- pydicom/_version.py
> Update _version.py for v1.4 dev

- README.md
~We may want to add~ I added this to the release ToDo list...
> Update DOI to pydicom 1.3 version

- setup.py
> Add python3.7 to allowed versions in setup.py

- doc/Makefile
- doc/old/image_data_handlers.rst
- doc/old/working_with_overlays.rst
- pydicom/pixel_data_handlers/util.py
Related to #826, #273 and #914
Documentation updates
* Add section on GDCM and color spaces
* Add section on the overlay origin
* Minor cleanup for API links, formatting, etc
> [MRG] Update pixel and overlay documentation

- examples/dicomtree.py
adding a title to the Tk window.
Plus one documentation comment on how to use it.
> add a title to the Tk window

- .travis.yml
- build_tools/travis/install.sh
- pydicom/pixel_data_handlers/pillow_handler.py
- pydicom/tests/test_environment.py
Closes #924 
* Switches from using private to public Pillow methods
* Travis pillow builds with 3.7 changed to use known good version (3.7.3)
> [MRG] Avoid using private Pillow modules

- doc/release_notes/v1.4.0.rst
- pydicom/dataset.py
- pydicom/tests/test_dataset.py
- fixes #947
see discussion in #947
> [MRG] Added workaround for error unpickling Dataset

- doc/release_notes/v1.4.0.rst
- pydicom/charset.py
- pydicom/tests/test_charset.py
fixes #917. This PR adds a function to encode Unicode into JIS X 0212.
> [MRG] Fix JIS X 0212 characters support

- pydicom/filereader.py
- closes #483
Minor docstring addition as discussed in #483.
> [MRG] Added usage note in data_element_generator docstring

- examples/memory_dataset.py
- closes #285
This adds a very simple example that shows how to work with DicomFileLike and BytesIO, along the lines of the example posted in the issue. [Here](https://314-65673081-gh.circle-artifacts.com/0/home/circleci/project/doc/_build/html/auto_examples/index.html) is the output (second example).
> [MRG] Added example for a reading/writing a dataset from/to bytes

- doc/release_notes/v1.4.0.rst
- pydicom/filereader.py
- pydicom/tests/test_filereader.py
> [MRG] Explicit vr heuristic in sequences

- doc/release_notes/v1.4.0.rst
- pydicom/dataset.py
- pydicom/tests/test_dataset.py
> [MRG] Add warning when saving compressed without encapsulation

- doc/release_notes/v1.4.0.rst
- pydicom/_dicom_dict.py
- pydicom/_uid_dict.py
- source/generate_dict/generate_dicom_dict.py
- adapted handling of retired attribute to changes in standard
- closes #1013
> [MRG] Updated DICOM dictionary to 2019e edition

- README.md
- pydicom/_version.py
Final version and README updates for v1.4 release.
> [MRG] Update version and README for 1.4 release

- README.md
Yet another badge, this time for Gitter (I looked for a link to Gitter at the pydicom page and couldn't find it, so decided to add this...)
> [MRG] Added badge for Gitter to Readme

- pydicom/_version.py
In preparation for patch release
> Update version to 1.4.1

- .travis.yml
- README.md
- appveyor.yml
- pydicom/_version.py
Version update in master to '2.0.0.dev0'
> Update version to dev 2.0.0

- README.md
- fixes #1044
just made this correction in the web editor...
> [MRG] Fixed documentation link in README

- doc/release_notes/v2.0.0.rst
- pydicom/dataelem.py
- pydicom/tests/test_filereader.py
> [MRG] Fix failure to read with empty LUT Descriptor

- dicom.py
- closes #1056
Just the URL, changed in web interface.
> Fixed URL to transition guide

- pydicom/pixel_data_handlers/util.py
- pydicom/tests/test_handler_util.py
> [MRG] Fix exception raised by apply_color_lut()

- doc/release_notes/v2.0.0.rst
- pydicom/pixel_data_handlers/util.py
- pydicom/tests/test_handler_util.py
> [MRG] Fix not handling LUT Data with VR OW

- doc/release_notes/v2.0.0.rst
- pydicom/dataset.py
- pydicom/tests/test_dataset.py
- fixes #1078
Hopefully the last problem with deferred item access...
> [MRG] Fixed access to private creator tag in raw datasets

- CONTRIBUTING.md
The CONTRIBUTING.md has a broken link to Sphinx
(I mostly ignored the tasks, given the nature of the change.)
> [MRG] Fix CONTRIBUTING.md link to Sphinx

- CONTRIBUTING.md
- added a point about commit messages - closes #631
- added a note about contrib-pydicom (see #790)
- removed some unneeded stuff, made some minor changes
> [MRG] Changes to the contributing guide

- doc/reference/config.rst
- doc/release_notes/v2.0.0.rst
- pydicom/config.py
- pydicom/tests/test_valuerep.py
Fixes a bug where config.DS_decimal does not set global flag use_DS_decimal as expected.
> [WIP] Fix config.DS_decimal() bug

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/pixel_issue.md
- CONTRIBUTING.md
- pydicom/env_info.py
- pydicom/tests/test_env_info.py
Emboldened by the comment at the end of https://github.com/pydicom/pydicom/pull/1091#discussion_r419688012, I took it upon myself to suggest an alternative snippet to gather system info for bug reports.
> [MRG] Make gathering system info easier

- doc/release_notes/v2.0.0.rst
- pydicom/dataset.py
- pydicom/tests/test_dataset.py
- try to minimize performance impact by removing all private blocks
and checking for existing private blocks first
- fixes #1097
> [MRG] Invalidate private blocks on deleting private creator

- pydicom/_dicom_dict.py
- source/generate_dict/generate_dicom_dict.py
One more task as part of v2 release...
Update DICOM dictionary, and remove Python 2 code from generate_dicom_dict.py
> Update DICOM dictionary to 2020b

- .github/FUNDING.yml
- pydicom/_version.py
Update version; add sponsorship file.  
Pushing to master first, then will merge to 2.0.X branch (had trouble going the other direction last release).
> [MRG] Update for 2.0 final release

- .github/workflows/master-push.yml
- .github/workflows/pythonpackage.yml
- pydicom/dataelem.py
- pydicom/dataset.py
- pydicom/tests/test_JPEG_LS_transfer_syntax.py
- pydicom/tests/test_charset.py
- pydicom/tests/test_codedict.py
- pydicom/tests/test_fileutil.py
- pydicom/tests/test_numpy_pixel_data.py
- pydicom/tests/test_pillow_pixel_data.py
- pydicom/tests/test_rle_pixel_data.py
* start a workflow for push to master (when merging a PR)
* update existing PR workflow linter for altered files only
* part of #1121
> [WIP] Add workflow for push to master, expanded CI matrix

- pydicom/uid.py
> [MRG] Add type hints for uid module

- pydicom/tests/test_valuerep.py
- pydicom/valuerep.py
Implemented ```__contains__```, ```__next__``` and ```__iter__``` for the PersonName class to make it iterable and able to check if certain characters are within the name.
Has no warnings with pyflakes and pycodestyle and passes all tests, included added tests for new methods, for ```valuerep.py```.
closes #1103
> [MRG] Added __contains__, __next__ and __iter__ to PersonName

- .github/workflows/master-push.yml
- .github/workflows/pythonpackage.yml
OK, the problem is that the `master` pull doesn't send any coverage reports to codecov so there's nothing for them to compare to when doing the PR coverage check
> [MRG] Send coverage reports on master pull workflow

- README.md
- doc/old/image_data_handlers.rst
- doc/tutorials/waveforms.rst
Closes #1174, updates README and fixes a couple of minor documentation things.
> [MRG] Update README

- doc/release_notes/v2.1.0.rst
- pydicom/charset.py
- pydicom/tests/test_charset.py
- do not warn as this is a benign error
- fixes #1190
> [MRG] Handle empty specific character set as default encoding

- doc/release_notes/v2.1.0.rst
- pydicom/filewriter.py
- pydicom/tests/test_filewriter.py
> [MRG] Fix empty ambiguous VR elements raising an exception

- pydicom/tag.py
- pydicom/uid.py
> [MRG] Add type hints to tag module

- doc/index.rst
- doc/release_notes/v2.1.0.rst
- pydicom/dicomdir.py
- pydicom/filereader.py
- pydicom/tests/test_dicomdir.py
- pydicom/tests/test_filereader.py
- pydicom/tests/test_fileset.py
> [MRG] Deprecate DicomDir and read_dicomdir()

- pydicom/dataelem.py
Add encoding as kwarg when calling data_element_callback in DataElement_from_raw to make it accessible to the data_element_callback. This argument is useful when writing callback on string VR. (e.g. fix backslash in string data element with VM=1).
For instance, I am using the following one:
```
def fix_backslash_in_VM1_string_callback(raw_elem, encodings=None):
encodings = encodings or [default_encoding]
if isinstance(encodings, str):
encodings = [encodings]
try:
vr, vm, _, _, _ = datadict.get_entry(raw_elem.tag)
except KeyError:
return raw_elem
if vr == raw_elem.VR and vm == "1":
if vr not in [
"UT",
"ST",
"LT",
"FL",
"FD",
"AT",
"OB",
"OW",
"OF",
"SL",
"SQ",
"SS",
"UL",
"OB/OW",
"OW/OB",
"OB or OW",
"OW or OB",
"UN",
"US",
]:
value = values.convert_value(raw_elem.VR, raw_elem)
if …
```
> [MRG] Add encoding as kwarg when calling data_element_callback

- .gitignore
- doc/release_notes/v2.1.0.rst
- doc/tutorials/dicom_json.rst
- pydicom/dataelem.py
- pydicom/dataset.py
- pydicom/jsonrep.py
- pydicom/tests/test_json.py
I believe that this PR is ready to merge. If I've missed a step (my first contribution to this project), please let me know and I will fix immediately.
**Note - I have not bumped the version numbering, as normally I leave that up to the project maintainer.**
- Added a new signature for `bulk_data_uri_handler` to the `from_json` methods in *dataelem.py*, *dataset.py* and `get_element_values` in *jasonrep.py*.
- Updated documentation in py files and in *dicom_json.rst*.
- Add a new test in *test_json.py* to test the new signature
> [MRG] closes #1227

- pydicom/charset.py
- pydicom/dataelem.py
- pydicom/dataset.py
- pydicom/filereader.py
- pydicom/multival.py
- pydicom/sequence.py
- pydicom/tests/test_filereader.py
- pydicom/tests/test_json.py
- pydicom/tests/test_multival.py
- pydicom/tests/test_sequence.py
- pydicom/tests/test_values.py
- pydicom/valuerep.py
- pydicom/values.py
* Refinements for existing hints
* Add hints for `values.py`
* Fix multivalued AE elements not decoding correctly
* Add `__iadd__` and `extend` to `Sequence` and `MultiValue`
> [MRG] Type hint refinements

- doc/old/working_with_overlays.rst
- doc/old/working_with_waveforms.rst
- doc/release_notes/v2.1.0.rst
- pydicom/pixel_data_handlers/numpy_handler.py
- pydicom/tests/test_numpy_pixel_data.py
Related to #1230
* Add support for ndarray input
* Pad odd length packed data by default
> [MRG] Improvements for pack_bits

- doc/reference/handlers.rst
- doc/release_notes/v2.1.0.rst
- pydicom/pixel_data_handlers/__init__.py
- pydicom/pixel_data_handlers/util.py
- pydicom/tests/test_handler_util.py
* Closes #1234, closes #1237
* Adds `apply_windowing()` and `apply_voi()` functions
> [MRG] Update apply_voi_lut

- README.md
- pydicom/_version.py
- setup.py
> Start v2.2 dev

- doc/release_notes/index.rst
- doc/release_notes/v2.1.1.rst
- pydicom/_version.py
- pydicom/filebase.py
- pydicom/tests/test_json.py
Bring in changes from 2.1.1
Hopefully this worked out correctly...
> Backport 2.1.1

- .github/workflows/pythonpackage.yml
- setup.py
* Bump the minimum supported Python version to 3.6.1
> [MRG] Bump minimum support Python version

- pydicom/config.py
- pydicom/dataset.py
- https://pydicom.github.io/pydicom/stable/reference/generated/pydicom.config.pixel_data_handlers.html#pydicom.config.pixel_data_handlers
- https://pydicom.github.io/pydicom/stable/reference/generated/pydicom.dataset.Dataset.html#pydicom.dataset.Dataset.decompress
I updated the description of the parameters.
> [MRG] Fix docstring for pixel_data_handlers

- doc/release_notes/v2.2.0.rst
Release note additions for the changes already merged in #1331
- [ N/A ] Unit tests added that reproduce the issue or prove feature is working (N/A)
- [ N/A ] Unit tests passing and overall coverage the same or better
> Add v2.2.0 release notes regarding Person Name

- pydicom/config.py
> [MRG] Add caveat to datetime_conversion documentation

- .github/workflows/master-push.yml
- .github/workflows/pythonpackage.yml
* Fix for failing master CI workflow by uninstalling -rle plugin
* Fix codecov reports not being correct
* Switch to codecov github action instead of using bash uploader
> [MRG] Updates to CI workflows

- pydicom/tests/test_valuerep.py
- pydicom/valuerep.py
- fixes #1371 (pickling of DT with time zone info)
- fixes usage of inherited methods
Turned out there was a much easier fix (as I hoped). I understood that because a couple of other tests I wrote for the other PR also failed, due to the fix number arguments in `__new__` and `__init__`.
> [MRG] Fix handling of arguments in DA, TM and DT classes

- pydicom/charset.py
- pydicom/dataelem.py
- pydicom/fileset.py
- pydicom/tests/test_fileset.py
> [MRG] Typing updates for charset and fileset

- doc/release_notes/v2.2.0.rst
- pydicom/_dicom_dict.py
- pydicom/_storage_sopclass_uids.py
- pydicom/_uid_dict.py
- pydicom/_version.py
> [MRG] Update data dictionaries to 2021b

- .github/PULL_REQUEST_TEMPLATE.md
- pydicom/charset.py
- pydicom/data/data_manager.py
- pydicom/dataelem.py
- pydicom/dataset.py
- pydicom/encoders/base.py
- pydicom/filereader.py
- pydicom/overlays/numpy_handler.py
- pydicom/pixel_data_handlers/gdcm_handler.py
- pydicom/pixel_data_handlers/pillow_handler.py
- pydicom/pixel_data_handlers/pylibjpeg_handler.py
- pydicom/pixel_data_handlers/rle_handler.py
- pydicom/pixel_data_handlers/util.py
- pydicom/values.py
- pydicom/waveforms/numpy_handler.py
50 outright typing errors left
> [MRG] Typing updates for dataset

- .github/PULL_REQUEST_TEMPLATE.md
- pydicom/charset.py
- pydicom/config.py
- pydicom/dataelem.py
- pydicom/dataset.py
- pydicom/encoders/base.py
- pydicom/filereader.py
- pydicom/fileset.py
- pydicom/filewriter.py
- pydicom/overlays/numpy_handler.py
- pydicom/pixel_data_handlers/gdcm_handler.py
- pydicom/pixel_data_handlers/jpeg_ls_handler.py
- pydicom/pixel_data_handlers/numpy_handler.py
- pydicom/pixel_data_handlers/pillow_handler.py
- pydicom/pixel_data_handlers/pylibjpeg_handler.py
- pydicom/pixel_data_handlers/rle_handler.py
- pydicom/pixel_data_handlers/util.py
- pydicom/sequence.py
- pydicom/tests/test_charset.py
- pydicom/tests/test_valuerep.py
- pydicom/uid.py
- pydicom/valuerep.py
- pydicom/values.py
- pydicom/waveforms/numpy_handler.py
All clean :smile: although that depends on what you run mypy with
There are 3 ignored errors that are [false-positives](https://github.com/python/typeshed/issues/5527).
There's still annotations that need to be added, but default mypy settings don't report any errors.
> [MRG] Add and update type hints

- .github/workflows/pr-typing.yml
- pydicom/tests/test_valuerep.py
- pydicom/valuerep.py
* Add `__hash__` to IS, DSfloat, DSdecimal
* Add typing packages required due to newer mypy version
> [MRG] Add __hash__ implementation to IS, DSfloat, DSdecimal

- doc/release_notes/v2.2.0.rst
- pydicom/pixel_data_handlers/rle_handler.py
- pydicom/tests/test_rle_pixel_data.py
> [MRG] Fix decoding padded RLE segments

- doc/release_notes/v2.2.0.rst
- doc/tutorials/contributing_docs.rst
- pydicom/_version.py
* update version for release candidate
* add missing release notes
[Release notes](https://3004-14006067-gh.circle-artifacts.com/0/doc/_build/html/release_notes/v2.2.0.html)
> Prep for v2.2 pre-release

- pydicom/filereader.py
- pydicom/fileutil.py
> [MRG] Allow DicomFileLike object as argument to dcmread

- doc/release_notes/v2.2.0.rst
- pydicom/pixel_data_handlers/numpy_handler.py
- pydicom/tests/test_numpy_pixel_data.py
> [MRG] Make Pixel Representation optional for decoding

- .github/workflows/master-push.yml
- README.md
- doc/release_notes/v2.2.0.rst
- pydicom/_version.py
- pydicom/filereader.py
- pydicom/fileutil.py
- pydicom/pixel_data_handlers/numpy_handler.py
- pydicom/tests/test_numpy_pixel_data.py
Simply rebase so that v2.2.0 release from the 2.2.X branch is in the master history.
> V2.2.0 in master

- pydicom/_version.py
> Update version to 2.3 dev

- examples/input_output/plot_read_fileset.py
- examples/input_output/plot_write_dicom.py
- pydicom/_version.py
- pydicom/charset.py
- pydicom/cli/main.py
- pydicom/cli/show.py
- pydicom/config.py
- pydicom/data/__init__.py
- pydicom/datadict.py
- pydicom/dicomdir.py
- pydicom/encoders/base.py
- pydicom/encoders/gdcm.py
- pydicom/encoders/native.py
- pydicom/filereader.py
- pydicom/jsonrep.py
- pydicom/misc.py
- pydicom/multival.py
- pydicom/pixel_data_handlers/pillow_handler.py
- pydicom/values.py
- source/generate_cids/generate_concept_dicts.py
- source/scripts/charlist.py
Fix some errors and warnings reported by LGTM:
https://lgtm.com/projects/g/pydicom/pydicom/alerts/
Some errors have been left for later, some warnings have been reported in dedicated issues #1469 and #1470.
> [MRG] Fix LGTM alerts

- pydicom/dataset.py
> [MRG] LGTM recommendation: Unused import

- pydicom/pixel_data_handlers/pillow_handler.py
Fix LGTM recommendation.
Fixes #1472.
> [MRG] LGTM recommendation: Unused local variable

- pydicom/dataset.py
This regular expression includes duplicate character 'z' in a set of characters.
> [MRG] LGTM warning: Duplication in regular expression character class

- lgtm.yml
Disable false positives that cannot be fixed by LGTM, because their heuristic detects strings such "id`"` that are actually very common in DICOM, for example in "`UID`".
> [MRG] Work around LGTM errors: Clear-text logging of sensitive information

- source/generate_dict/generate_private_dict.py
This one has **not** been found by [codespell](https://github.com/codespell-project/codespell):!
Also improved a comment by simplifying it.
> [MRG] Fix typo

- .github/codespell_ignore_words.txt
- .github/workflows/codespell.yml
- setup.cfg
Run [codespell](https://github.com/codespell-project/codespell) in CI to catch typos early on.
Use GitHub Actions with [actions-codespell](https://github.com/codespell-project/actions-codespell).
> [MRG] Add codespell to CI to detect typos early

- pydicom/_version.py
> [MRG] Update __dicom_version__ to reflect currently used version of the standard

- doc/tutorials/dataset_basics.rst
> [MRG] Fix typo in dataset basics tutorial

- pydicom/tests/test_dataelem.py
- pydicom/tests/test_dictionary.py
- pydicom/tests/test_overlay_np.py
- pydicom/tests/test_util.py
- pydicom/tests/test_waveform.py
- reset changed environment
- fixes #1540
> [MRG] Make sure the same tests can be run more than once

- pydicom/tag.py
> [MRG] Fix docstring for tag.Tag

- pydicom/dataset.py
- pydicom/encoders/base.py
- pydicom/filebase.py
- pydicom/fileset.py
- pydicom/filewriter.py
- pydicom/pixel_data_handlers/util.py
- pydicom/tests/test_handler_util.py
- pydicom/valuerep.py
* Closes #1554
* Checks for empty sequences in the pixel visualisation functions
> [MRG] Check for empty sequence in pixel visualisation functions

- pydicom/dataelem.py
- source/generate_cids/generate_concept_dicts.py
Fix these LGTM.com recommendations:
https://lgtm.com/projects/g/pydicom/pydicom/snapshot/eac82edaea40e6dd763be96bfdc3cf98efeb804d/files/pydicom/dataelem.py?sort=name&dir=ASC&mode=heatmap#x99c7b17b1f63e5bf:1
https://lgtm.com/projects/g/pydicom/pydicom/snapshot/eac82edaea40e6dd763be96bfdc3cf98efeb804d/files/source/generate_cids/generate_concept_dicts.py?sort=name&dir=ASC&mode=heatmap#xa78433b72cd1b9c8:1
> [MRG] LGTM recommendations

- doc/release_notes/v2.3.0.rst
- pydicom/config.py
- as proposed by @mshunshin
- fixes #1487
Just changes the order as poposed in the issue, does not change behavior as mentioned in the comments.
> [MRG] Use rle-handler as last handler for RLE to prefer faster handlers

- pydicom/tests/test_util.py
- pydicom/util/fixer.py
This fixes two bugs in `fixer.fix_separator`:
* Elements with a VR in `for_VRs` with a null /`None` value  would raise a `NameError` for `new_value` in the callback while the fixer was active
* The `process_unknown_VRs` flag was not being passed down from `fix_separator` to `fix_separator_callback` or referred to with the right name. This resulted in a  `KeyError` when accessing any unknown VR tag while the fixer was active.
And one half-bugfix / half-feature:
* Due to the frequent use of trailing spaces in DICOM, when the `invalid_separator` was a space, extra blank items would be added to the end of elements, even elements with VM of 1; e.g. `ds.ImagePositionPatient [0.1, 0.2, 0.3, '']` or `ds.EchoTime [0.9, '']`.
* It may be hard to believe that spaces would be used as separators, but …
> [MRG] Fix issues with fix_separator and callback

- doc/release_notes/v2.3.0.rst
- pydicom/dataset.py
- pydicom/tests/test_dataset.py
* Closes #1599 
* Adds class attributes to `Dataset.__dir__()`
> [MRG] Add class attributes to Dataset.__dir__()

- README.md
- pydicom/_version.py
Housekeeping for dev after v2.3 release
> Update version and DOI post v2.3 release

- doc/release_notes/index.rst
- doc/release_notes/v2.4.0.rst
- examples/input_output/plot_read_dicom.py
- pydicom/tests/test_valuerep.py
- pydicom/valuerep.py
- Add `alphabetic` property to PersonName VR.
- Added tests for `ideographic` and `phonetic` properties.
- Modify example to use `family_comma_given` method from PersonName VR
> [MRG] Add alphabetic property to PersonName VR

- .github/workflows/merge-typing.yml
Pin mypy in the merge workflow
> [MRG] Also pin mypy in the merge workflow

- pydicom/_dicom_dict.py
- pydicom/_uid_dict.py
- pydicom/_version.py
New DICOM dictionary updates [were released](https://groups.google.com/g/comp.protocols.dicom/c/lUooZtJHkk4).
Ran the generate_dict and generate_uid scripts to update.
> [MRG] Update DICOM and UID dicts to 2022e

- README.md
Removed inactive gitter badge from README.
Closes #1755.
> [MRG] Removed inactive gitter badge

- doc/release_notes/v2.4.0.rst
- pydicom/_dicom_dict.py
- pydicom/_uid_dict.py
- pydicom/_version.py
Update to 2023b DICOM dictionaries in preparation for 2.4 release
> Dicom2023b

- .github/workflows/publish-pypi-deploy.yml
- pydicom/_version.py
- pyproject.toml
Final changes (hopefully) for 2.4 release.  I've reassigned some remaining issues to v3.0, I think we should just get this out.
> [MRG] Prep v2.4

- pyproject.toml
- tests/test_dataelem.py
- tests/test_dataset.py
- tests/test_filewriter.py
- tests/test_valuerep.py
I found GitHub action failures while working on a different pull request. Changes in this PR include:
- Suppressed ruff errors about checking equality of an object with itself, since that is the intent of the tests.
- Added a `[dev]` section to `pyproject.toml` to make it easy to install packages needed for development
> [MRG] Fix unit test warnings and ruff failures

- src/pydicom/filewriter.py
- tests/test_filewriter.py
> Add None parent failing test

- doc/reference/elem.valuerep.rst
- doc/release_notes/v3.0.0.rst
- examples/show_charset_name.py
- src/pydicom/valuerep.py
- tests/test_valuerep.py
* Removes `PersonNameUnicode` as per planned deprecation
* Updates docs accordingly
> [MRG] Remove deprecated PersonNameUnicode class

- .github/workflows/PR.yml
- .github/workflows/tests_wf.yml
Fix coverage not being calculated for merge with Windows workflow
Working run: https://github.com/pydicom/pydicom/actions/runs/5791448931/job/15696281229
> [MRG] Workflow fix for codecov on merge with Windows

- .github/workflows/merge.yml
- .github/workflows/tests_wf.yml
Fix numpy build with PyPy3.10 (current numpy version has no wheels for pypy3.10)
Failing workflow: https://github.com/pydicom/pydicom/actions/runs/6450801026/job/17510591046
Working workflow: https://github.com/pydicom/pydicom/actions/runs/6502192391/job/17660808189
> [MRG] Fix merge workflow for PyPy3.10 failure to build numpy

- doc/old/private_data_elements.rst
- examples/metadata_processing/plot_add_dict_entries.py
- add section about adding dictionary entries to user guide
- see #1900
> [MRG] Fix example for adding private dictionary entries

- doc/release_notes/v3.0.0.rst
- src/pydicom/overlay_data_handlers/__init__.py
- tests/test_dataset.py
- tests/test_overlay_np.py
Removes the `overlay_data_handlers` module
> [MRG] Remove overlay_data_handlers module

- doc/reference/uid.rst
- doc/release_notes/v3.0.0.rst
- src/pydicom/_dicom_dict.py
- src/pydicom/_uid_dict.py
- src/pydicom/_version.py
- src/pydicom/uid.py
Update to 2023e version of the DICOM Standard, related to #1848
> [MRG] Update to 2023e version of DICOM Standard

- src/pydicom/fileset.py
- tests/test_fileset.py
> [MRG] FileSet.__str__ show SeriesDescription.

- doc/release_notes/v3.0.0.rst
- src/pydicom/charset.py
- src/pydicom/data/data_manager.py
- src/pydicom/data/download.py
- src/pydicom/datadict.py
- src/pydicom/dataelem.py
- src/pydicom/dataset.py
- src/pydicom/encaps.py
- src/pydicom/filereader.py
- src/pydicom/fileset.py
- src/pydicom/filewriter.py
- src/pydicom/jsonrep.py
- src/pydicom/misc.py
- src/pydicom/overlays/numpy_handler.py
- src/pydicom/pixel_data_handlers/numpy_handler.py
- src/pydicom/pixel_data_handlers/pillow_handler.py
- src/pydicom/pixel_data_handlers/rle_handler.py
- src/pydicom/pixel_data_handlers/util.py
- src/pydicom/valuerep.py
- tests/test_misc.py
Wrap warnings so they can be logged, closes #1529
> [MRG] Capture warnings for logging

- tests/test_encoders.py
- tests/test_fileset.py
> [MRG] Fixes for intermittent test failures

- doc/release_notes/v3.0.0.rst
- doc/tutorials/dicom_json.rst
- doc/tutorials/sr_basics.rst
- src/pydicom/charset.py
- src/pydicom/config.py
- src/pydicom/data/data_manager.py
- src/pydicom/datadict.py
- src/pydicom/dataelem.py
- src/pydicom/dataset.py
- src/pydicom/jsonrep.py
- src/pydicom/overlays/numpy_handler.py
- src/pydicom/pixel_data_handlers/numpy_handler.py
- src/pydicom/pixel_data_handlers/util.py
- src/pydicom/tag.py
- src/pydicom/uid.py
- src/pydicom/valuerep.py
- src/pydicom/values.py
- tests/test_dataset.py
- tests/test_overlay_np.py
* Removes `.. versionadded` and `.. versionchanged` for < v2.0 (except in encaps module)
* Removes `config.overlay_data_handlers`
> [MRG] Remove config.overlay_data_handers and old sphinx directives

- src/pydicom/dataelem.py
- tests/test_dataelem.py
* Closes #1307, changes repr(sequence) to str(sequence).
> [MRG] Make repr() for SQ elements consistent with other elements

- .github/workflows/tests_wf.yml
Possibly fix the codecov upload failures
> [MRG] Add token for codecov

- tests/test_overlay_np.py
- tests/test_pillow_pixel_data.py
> [MRG] Minor test cleanup

- doc/release_notes/v3.0.0.rst
- src/pydicom/dataset.py
- tests/test_dataset.py
Fixes `RecursionError` on deepcopy of a private block.
Closes #2025
> [MRG] Fix RecursionError with deepcopy on a private block

- doc/release_notes/v3.0.0.rst
- src/pydicom/pixel_data_handlers/pillow_handler.py
- src/pydicom/pixel_data_handlers/pylibjpeg_handler.py
- src/pydicom/pixels/decoders/pillow.py
- src/pydicom/pixels/decoders/pylibjpeg.py
- src/pydicom/pixels/encoders/pylibjpeg.py
- src/pydicom/pixels/processing.py
- tests/pixels/test_encoder_pylibjpeg.py
- tests/pixels/test_processing.py
- tests/test_pylibjpeg.py
* Adds support for numpy 2.0
* Some type hints updates for the pixel plugins
* Test fixes for lossy J2K on MacOS
Close #2075
> [MRG] Add support for numpy v2.0

- doc/reference/index.rst
- doc/reference/sr.rst
- doc/release_notes/v3.0.0.rst
- src/pydicom/sr/__init__.py
- src/pydicom/sr/codedict.py
- tests/test_codes.py
* Refactors the `pydicom.sr` interface to simplify the access types and to make public
* Adds `sr` module to reference API docs
Closes #1454
> [MRG] Refactor concepts interface

- .pre-commit-config.yaml
- CONTRIBUTING.md
- doc/fix_search.py
- doc/guides/user/base_element.rst
- doc/guides/user/viewing_images.rst
- doc/tutorials/contributing.rst
- examples/metadata_processing/plot_add_dict_entries.py
- pyproject.toml
- src/pydicom/config.py
- src/pydicom/filebase.py
- src/pydicom/pixels/common.py
- src/pydicom/pixels/decoders/base.py
- tests/pixels/pixels_reference.py
- tests/test_valuerep.py
- tests/test_values.py
- util/generate_dict/generate_uid_dict.py
* Removes mentions of `contrib-pydicom`
* Updates contribution guide
* Closes #790 (although the repo still needs archiving?)
> [MRG] Remove contrib-pydicom, update contribution guide

- tests/test_dataset.py
Fixes test failure on PyPy due to different exception message.
> [MRG] Update deepcopy test to account for PyPy

- pyproject.toml
Apply some [Repo-Review](https://learn.scientific-python.org/development/guides/repo-review/?repo=pydicom%2Fpydicom&branch=main) rules.
> [MRG] Apply some Repo-Review rules

- pyproject.toml
- src/pydicom/dataset.py
- src/pydicom/encaps.py
- src/pydicom/fileset.py
- src/pydicom/pixels/processing.py
- util/generate_cids/generate_concept_dicts.py
> [MRG] Enforce ruff/Perflint rules except PERF203

- doc/conf.py
- pyproject.toml
- src/pydicom/cli/main.py
- src/pydicom/data/retry.py
- src/pydicom/dataelem.py
- src/pydicom/dataset.py
- src/pydicom/fileset.py
- src/pydicom/filewriter.py
- src/pydicom/tag.py
- src/pydicom/util/leanread.py
- src/pydicom/valuerep.py
- tests/test_filereader.py
- tests/test_pillow_pixel_data.py
- tests/test_pylibjpeg.py
- util/generate_dict/generate_dicom_dict.py
- util/generate_dict/generate_private_dict.py
- util/generate_dict/generate_uid_dict.py
- util/generate_uids/generate_storage_sopclass_uids.py
RUF010 Use explicit conversion flag
RUF100 Unused blanket `noqa` directive
> Apply assorted ruff rules (RUF010 and RUF100)

- src/pydicom/filebase.py
- src/pydicom/pixels/common.py
- src/pydicom/pixels/processing.py
- src/pydicom/pixels/utils.py
TCH003 Move standard library import into a type-checking block
> [MRG] Apply ruff/flake8-type-checking rule TCH003

- doc/release_notes/v3.0.0.rst
- src/pydicom/dataset.py
- src/pydicom/filewriter.py
- tests/test_dataset.py
- tests/test_fileset.py
- tests/test_filewriter.py
Change from `exist_ok` to `overwrite`
> [MRG] Change arg name to overwrite

- doc/release_notes/v3.0.0.rst
- pyproject.toml
* Bumps to 3.0.0-rc1
* Add short summary of main breaking changes to release notes
> [MRG] Bump version to RC1

- README.md
- pyproject.toml
* Bumps to v3.0
* Minor change to README to use `examples` module
I was going to give RC1 another week or two, but I'll be unavailable from ~21/9-5/10 so an earlier release makes more sense.
> [MRG] Bump version for v3.0 release

- doc/release_notes/v3.1.0.rst
- src/pydicom/dataset.py
- tests/test_dataset.py
* Convert `Dataset.is_decompressed` to a convenience property
* Closes #2155
> [MRG] Update Dataset.is_decompressed and document it

- .pre-commit-config.yaml
- src/pydicom/filereader.py
- util/generate_cids/generate_concept_dicts.py
- util/generate_dict/generate_private_dict.py
Address `UP031` warning reported after the upgrade.
> [MRG] Bump ruff from 0.5.1 to 0.9.1
